//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for HealthStatus.
const (
	Ok HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for Layer.
const (
	Administration         Layer = "administration"
	Applicative            Layer = "applicative"
	Business               Layer = "business"
	Ecosystem              Layer = "ecosystem"
	InfrastructureLogical  Layer = "infrastructure_logical"
	InfrastructurePhysical Layer = "infrastructure_physical"
)

// Valid indicates whether the value is a known member of the Layer enum.
func (e Layer) Valid() bool {
	switch e {
	case Administration:
		return true
	case Applicative:
		return true
	case Business:
		return true
	case Ecosystem:
		return true
	case InfrastructureLogical:
		return true
	case InfrastructurePhysical:
		return true
	default:
		return false
	}
}

// Defines values for ServiceType.
const (
	ClusterIP    ServiceType = "ClusterIP"
	ExternalName ServiceType = "ExternalName"
	LoadBalancer ServiceType = "LoadBalancer"
	NodePort     ServiceType = "NodePort"
)

// Valid indicates whether the value is a known member of the ServiceType enum.
func (e ServiceType) Valid() bool {
	switch e {
	case ClusterIP:
		return true
	case ExternalName:
		return true
	case LoadBalancer:
		return true
	case NodePort:
		return true
	default:
		return false
	}
}

// Defines values for WorkloadKind.
const (
	DaemonSet   WorkloadKind = "DaemonSet"
	Deployment  WorkloadKind = "Deployment"
	StatefulSet WorkloadKind = "StatefulSet"
)

// Valid indicates whether the value is a known member of the WorkloadKind enum.
func (e WorkloadKind) Valid() bool {
	switch e {
	case DaemonSet:
		return true
	case Deployment:
		return true
	case StatefulSet:
		return true
	default:
		return false
	}
}

// Cluster defines model for Cluster.
type Cluster struct {
	// ApiEndpoint Kubernetes API server URL (informational).
	ApiEndpoint *string    `json:"api_endpoint,omitempty"`
	CreatedAt   *time.Time `json:"created_at,omitempty"`

	// DisplayName Human-friendly label, free-form.
	DisplayName *string `json:"display_name,omitempty"`

	// Environment Free-form environment tag (e.g., dev, staging, prod).
	Environment *string             `json:"environment,omitempty"`
	Id          *openapi_types.UUID `json:"id,omitempty"`

	// KubernetesVersion Cluster API server version reported by Kubernetes (e.g. "1.29.5").
	KubernetesVersion *string `json:"kubernetes_version,omitempty"`

	// Labels Arbitrary user-supplied string key/value labels.
	Labels *map[string]string `json:"labels,omitempty"`

	// Layer Always `infrastructure_logical` for Cluster. Set by the server.
	Layer *Layer `json:"layer,omitempty"`
	Name  string `json:"name"`

	// Provider Underlying Kubernetes distribution or hosting provider.
	// Open-ended; common values: gke, eks, aks, openshift, rke, kubeadm, onprem, other.
	Provider  *string    `json:"provider,omitempty"`
	Region    *string    `json:"region,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// ClusterCreate defines model for ClusterCreate.
type ClusterCreate struct {
	// ApiEndpoint Kubernetes API server URL (informational).
	ApiEndpoint *string `json:"api_endpoint,omitempty"`

	// DisplayName Human-friendly label, free-form.
	DisplayName *string `json:"display_name,omitempty"`

	// Environment Free-form environment tag (e.g., dev, staging, prod).
	Environment *string `json:"environment,omitempty"`

	// KubernetesVersion Cluster API server version reported by Kubernetes (e.g. "1.29.5").
	KubernetesVersion *string `json:"kubernetes_version,omitempty"`

	// Labels Arbitrary user-supplied string key/value labels.
	Labels *map[string]string `json:"labels,omitempty"`

	// Name Stable slug-like identifier, unique across the CMDB.
	// Immutable after creation.
	Name string `json:"name"`

	// Provider Underlying Kubernetes distribution or hosting provider.
	// Open-ended; common values: gke, eks, aks, openshift, rke, kubeadm, onprem, other.
	Provider *string `json:"provider,omitempty"`
	Region   *string `json:"region,omitempty"`
}

// ClusterList Paged list of clusters.
type ClusterList struct {
	Items []Cluster `json:"items"`

	// NextCursor Opaque cursor to pass as `?cursor=` to fetch the next page.
	// Absent or null when no more pages remain.
	NextCursor *string `json:"next_cursor,omitempty"`
}

// ClusterMutable Fields on a Cluster that clients may set and later update.
type ClusterMutable struct {
	// ApiEndpoint Kubernetes API server URL (informational).
	ApiEndpoint *string `json:"api_endpoint,omitempty"`

	// DisplayName Human-friendly label, free-form.
	DisplayName *string `json:"display_name,omitempty"`

	// Environment Free-form environment tag (e.g., dev, staging, prod).
	Environment *string `json:"environment,omitempty"`

	// KubernetesVersion Cluster API server version reported by Kubernetes (e.g. "1.29.5").
	KubernetesVersion *string `json:"kubernetes_version,omitempty"`

	// Labels Arbitrary user-supplied string key/value labels.
	Labels *map[string]string `json:"labels,omitempty"`

	// Provider Underlying Kubernetes distribution or hosting provider.
	// Open-ended; common values: gke, eks, aks, openshift, rke, kubeadm, onprem, other.
	Provider *string `json:"provider,omitempty"`
	Region   *string `json:"region,omitempty"`
}

// ClusterUpdate Fields on a Cluster that clients may set and later update.
type ClusterUpdate = ClusterMutable

// Health defines model for Health.
type Health struct {
	Status HealthStatus `json:"status"`

	// Version Build version of the running argosd.
	Version *string `json:"version,omitempty"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// Ingress defines model for Ingress.
type Ingress struct {
	CreatedAt *time.Time          `json:"created_at,omitempty"`
	Id        *openapi_types.UUID `json:"id,omitempty"`

	// IngressClassName IngressClass name the controller binds to (e.g., "nginx", "traefik").
	IngressClassName *string `json:"ingress_class_name,omitempty"`

	// Labels Arbitrary user-supplied string key/value labels.
	Labels *map[string]string `json:"labels,omitempty"`

	// Layer Always `applicative` for Ingress. See ADR-0004.
	Layer       *Layer             `json:"layer,omitempty"`
	Name        string             `json:"name"`
	NamespaceId openapi_types.UUID `json:"namespace_id"`

	// Rules Ingress routing rules. Opaque in v1: each entry carries whatever the
	// collector chose to persist (host, path, path_type, backend service
	// name / port).
	Rules *[]map[string]interface{} `json:"rules,omitempty"`

	// Tls TLS configuration entries. Opaque in v1: each entry carries hosts
	// and the referenced Secret name.
	Tls       *[]map[string]interface{} `json:"tls,omitempty"`
	UpdatedAt *time.Time                `json:"updated_at,omitempty"`
}

// IngressCreate defines model for IngressCreate.
type IngressCreate struct {
	// IngressClassName IngressClass name the controller binds to (e.g., "nginx", "traefik").
	IngressClassName *string `json:"ingress_class_name,omitempty"`

	// Labels Arbitrary user-supplied string key/value labels.
	Labels *map[string]string `json:"labels,omitempty"`

	// Name Kubernetes ingress name (DNS-label style). Unique per namespace.
	// Immutable after creation.
	Name string `json:"name"`

	// NamespaceId Parent namespace id. Immutable after creation; the namespace
	// must already exist or the create returns 404.
	NamespaceId openapi_types.UUID `json:"namespace_id"`

	// Rules Ingress routing rules. Opaque in v1: each entry carries whatever the
	// collector chose to persist (host, path, path_type, backend service
	// name / port).
	Rules *[]map[string]interface{} `json:"rules,omitempty"`

	// Tls TLS configuration entries. Opaque in v1: each entry carries hosts
	// and the referenced Secret name.
	Tls *[]map[string]interface{} `json:"tls,omitempty"`
}

// IngressList Paged list of ingresses.
type IngressList struct {
	Items []Ingress `json:"items"`

	// NextCursor Opaque cursor to pass as `?cursor=` to fetch the next page.
	// Absent or null when no more pages remain.
	NextCursor *string `json:"next_cursor,omitempty"`
}

// IngressMutable Fields on an Ingress that clients may set and later update.
type IngressMutable struct {
	// IngressClassName IngressClass name the controller binds to (e.g., "nginx", "traefik").
	IngressClassName *string `json:"ingress_class_name,omitempty"`

	// Labels Arbitrary user-supplied string key/value labels.
	Labels *map[string]string `json:"labels,omitempty"`

	// Rules Ingress routing rules. Opaque in v1: each entry carries whatever the
	// collector chose to persist (host, path, path_type, backend service
	// name / port).
	Rules *[]map[string]interface{} `json:"rules,omitempty"`

	// Tls TLS configuration entries. Opaque in v1: each entry carries hosts
	// and the referenced Secret name.
	Tls *[]map[string]interface{} `json:"tls,omitempty"`
}

// IngressUpdate Fields on an Ingress that clients may set and later update.
type IngressUpdate = IngressMutable

// Layer ANSSI cartography layer the asset belongs to. See ADR-0002 for the
// kind-to-layer mapping and the rationale behind the six-layer model.
type Layer string

// Namespace defines model for Namespace.
type Namespace struct {
	ClusterId openapi_types.UUID `json:"cluster_id"`
	CreatedAt *time.Time         `json:"created_at,omitempty"`

	// DisplayName Human-friendly label, free-form.
	DisplayName *string             `json:"display_name,omitempty"`
	Id          *openapi_types.UUID `json:"id,omitempty"`

	// Labels Arbitrary user-supplied string key/value labels.
	Labels *map[string]string `json:"labels,omitempty"`

	// Layer Always `infrastructure_logical` for Namespace. Set by the server.
	Layer *Layer `json:"layer,omitempty"`
	Name  string `json:"name"`

	// Phase Kubernetes namespace phase as last observed (e.g. "Active", "Terminating").
	// Open-ended to accommodate any additional phases Kubernetes introduces.
	Phase     *string    `json:"phase,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// NamespaceCreate defines model for NamespaceCreate.
type NamespaceCreate struct {
	// ClusterId Parent cluster id. Immutable after creation; the cluster must
	// already exist or the create returns 404.
	ClusterId openapi_types.UUID `json:"cluster_id"`

	// DisplayName Human-friendly label, free-form.
	DisplayName *string `json:"display_name,omitempty"`

	// Labels Arbitrary user-supplied string key/value labels.
	Labels *map[string]string `json:"labels,omitempty"`

	// Name Kubernetes namespace name (DNS-label style). Unique per cluster.
	// Immutable after creation.
	Name string `json:"name"`

	// Phase Kubernetes namespace phase as last observed (e.g. "Active", "Terminating").
	// Open-ended to accommodate any additional phases Kubernetes introduces.
	Phase *string `json:"phase,omitempty"`
}

// NamespaceList Paged list of namespaces.
type NamespaceList struct {
	Items []Namespace `json:"items"`

	// NextCursor Opaque cursor to pass as `?cursor=` to fetch the next page.
	// Absent or null when no more pages remain.
	NextCursor *string `json:"next_cursor,omitempty"`
}

// NamespaceMutable Fields on a Namespace that clients may set and later update.
type NamespaceMutable struct {
	// DisplayName Human-friendly label, free-form.
	DisplayName *string `json:"display_name,omitempty"`

	// Labels Arbitrary user-supplied string key/value labels.
	Labels *map[string]string `json:"labels,omitempty"`

	// Phase Kubernetes namespace phase as last observed (e.g. "Active", "Terminating").
	// Open-ended to accommodate any additional phases Kubernetes introduces.
	Phase *string `json:"phase,omitempty"`
}

// NamespaceUpdate Fields on a Namespace that clients may set and later update.
type NamespaceUpdate = NamespaceMutable

// Node defines model for Node.
type Node struct {
	// Architecture CPU architecture. Open-ended; common values: amd64, arm64, ppc64le, s390x.
	Architecture *string            `json:"architecture,omitempty"`
	ClusterId    openapi_types.UUID `json:"cluster_id"`
	CreatedAt    *time.Time         `json:"created_at,omitempty"`

	// DisplayName Human-friendly label, free-form.
	DisplayName *string             `json:"display_name,omitempty"`
	Id          *openapi_types.UUID `json:"id,omitempty"`

	// KubeletVersion Kubelet git version as reported by Kubernetes (e.g. "v1.29.5").
	KubeletVersion *string `json:"kubelet_version,omitempty"`

	// Labels Arbitrary user-supplied string key/value labels.
	Labels *map[string]string `json:"labels,omitempty"`

	// Layer Always `infrastructure_physical` for Node. Set by the server.
	Layer *Layer `json:"layer,omitempty"`
	Name  string `json:"name"`

	// OsImage Node OS image string (e.g. "Ubuntu 22.04.3 LTS").
	OsImage   *string    `json:"os_image,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// NodeCreate defines model for NodeCreate.
type NodeCreate struct {
	// Architecture CPU architecture. Open-ended; common values: amd64, arm64, ppc64le, s390x.
	Architecture *string `json:"architecture,omitempty"`

	// ClusterId Parent cluster id. Immutable after creation; the cluster must
	// already exist or the create returns 404.
	ClusterId openapi_types.UUID `json:"cluster_id"`

	// DisplayName Human-friendly label, free-form.
	DisplayName *string `json:"display_name,omitempty"`

	// KubeletVersion Kubelet git version as reported by Kubernetes (e.g. "v1.29.5").
	KubeletVersion *string `json:"kubelet_version,omitempty"`

	// Labels Arbitrary user-supplied string key/value labels.
	Labels *map[string]string `json:"labels,omitempty"`

	// Name Kubernetes node name (DNS-subdomain style). Unique per cluster.
	// Immutable after creation.
	Name string `json:"name"`

	// OsImage Node OS image string (e.g. "Ubuntu 22.04.3 LTS").
	OsImage *string `json:"os_image,omitempty"`
}

// NodeList Paged list of nodes.
type NodeList struct {
	Items []Node `json:"items"`

	// NextCursor Opaque cursor to pass as `?cursor=` to fetch the next page.
	// Absent or null when no more pages remain.
	NextCursor *string `json:"next_cursor,omitempty"`
}

// NodeMutable Fields on a Node that clients may set and later update.
type NodeMutable struct {
	// Architecture CPU architecture. Open-ended; common values: amd64, arm64, ppc64le, s390x.
	Architecture *string `json:"architecture,omitempty"`

	// DisplayName Human-friendly label, free-form.
	DisplayName *string `json:"display_name,omitempty"`

	// KubeletVersion Kubelet git version as reported by Kubernetes (e.g. "v1.29.5").
	KubeletVersion *string `json:"kubelet_version,omitempty"`

	// Labels Arbitrary user-supplied string key/value labels.
	Labels *map[string]string `json:"labels,omitempty"`

	// OsImage Node OS image string (e.g. "Ubuntu 22.04.3 LTS").
	OsImage *string `json:"os_image,omitempty"`
}

// NodeUpdate Fields on a Node that clients may set and later update.
type NodeUpdate = NodeMutable

// Pod defines model for Pod.
type Pod struct {
	CreatedAt *time.Time          `json:"created_at,omitempty"`
	Id        *openapi_types.UUID `json:"id,omitempty"`

	// Labels Arbitrary user-supplied string key/value labels.
	Labels *map[string]string `json:"labels,omitempty"`

	// Layer Always `applicative` for Pod. Set by the server.
	Layer       *Layer             `json:"layer,omitempty"`
	Name        string             `json:"name"`
	NamespaceId openapi_types.UUID `json:"namespace_id"`

	// NodeName Name of the node the pod is scheduled on.
	NodeName *string `json:"node_name,omitempty"`

	// Phase Kubernetes pod phase as last observed: Pending, Running, Succeeded,
	// Failed, or Unknown. Open-ended to accommodate any additional phases.
	Phase *string `json:"phase,omitempty"`

	// PodIp Pod IP address (IPv4 or IPv6). Informational; not validated as an
	// IP literal.
	PodIp     *string    `json:"pod_ip,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// PodCreate defines model for PodCreate.
type PodCreate struct {
	// Labels Arbitrary user-supplied string key/value labels.
	Labels *map[string]string `json:"labels,omitempty"`

	// Name Kubernetes pod name (DNS-subdomain style). Unique per namespace.
	// Immutable after creation.
	Name string `json:"name"`

	// NamespaceId Parent namespace id. Immutable after creation; the namespace
	// must already exist or the create returns 404.
	NamespaceId openapi_types.UUID `json:"namespace_id"`

	// NodeName Name of the node the pod is scheduled on.
	NodeName *string `json:"node_name,omitempty"`

	// Phase Kubernetes pod phase as last observed: Pending, Running, Succeeded,
	// Failed, or Unknown. Open-ended to accommodate any additional phases.
	Phase *string `json:"phase,omitempty"`

	// PodIp Pod IP address (IPv4 or IPv6). Informational; not validated as an
	// IP literal.
	PodIp *string `json:"pod_ip,omitempty"`
}

// PodList Paged list of pods.
type PodList struct {
	Items []Pod `json:"items"`

	// NextCursor Opaque cursor to pass as `?cursor=` to fetch the next page.
	// Absent or null when no more pages remain.
	NextCursor *string `json:"next_cursor,omitempty"`
}

// PodMutable Fields on a Pod that clients may set and later update.
type PodMutable struct {
	// Labels Arbitrary user-supplied string key/value labels.
	Labels *map[string]string `json:"labels,omitempty"`

	// NodeName Name of the node the pod is scheduled on.
	NodeName *string `json:"node_name,omitempty"`

	// Phase Kubernetes pod phase as last observed: Pending, Running, Succeeded,
	// Failed, or Unknown. Open-ended to accommodate any additional phases.
	Phase *string `json:"phase,omitempty"`

	// PodIp Pod IP address (IPv4 or IPv6). Informational; not validated as an
	// IP literal.
	PodIp *string `json:"pod_ip,omitempty"`
}

// PodUpdate Fields on a Pod that clients may set and later update.
type PodUpdate = PodMutable

// Problem RFC 7807 problem details.
type Problem struct {
	Detail *string `json:"detail,omitempty"`

	// Errors Field-level validation errors, when applicable.
	Errors *[]struct {
		Field   string `json:"field"`
		Message string `json:"message"`
	} `json:"errors,omitempty"`
	Instance *string `json:"instance,omitempty"`
	Status   int     `json:"status"`
	Title    string  `json:"title"`
	Type     string  `json:"type"`
}

// Service defines model for Service.
type Service struct {
	// ClusterIp Assigned ClusterIP (empty for Headless / ExternalName services).
	ClusterIp *string             `json:"cluster_ip,omitempty"`
	CreatedAt *time.Time          `json:"created_at,omitempty"`
	Id        *openapi_types.UUID `json:"id,omitempty"`

	// Labels Arbitrary user-supplied string key/value labels.
	Labels *map[string]string `json:"labels,omitempty"`

	// Layer Always `applicative` for Service. Set by the server.
	Layer       *Layer             `json:"layer,omitempty"`
	Name        string             `json:"name"`
	NamespaceId openapi_types.UUID `json:"namespace_id"`

	// Ports Service ports. Opaque in v1: each entry carries whatever the
	// collector chose to persist (name, port, target_port, protocol, node_port).
	Ports *[]map[string]interface{} `json:"ports,omitempty"`

	// Selector Pod label selector. Pods matching every key/value are selected.
	Selector *map[string]string `json:"selector,omitempty"`

	// Type Kubernetes Service type. Casing matches the enum Kubernetes itself
	// emits. Open-ended at the schema layer to accommodate future additions;
	// handler validation enforces the v1 subset.
	Type      *ServiceType `json:"type,omitempty"`
	UpdatedAt *time.Time   `json:"updated_at,omitempty"`
}

// ServiceCreate defines model for ServiceCreate.
type ServiceCreate struct {
	// ClusterIp Assigned ClusterIP (empty for Headless / ExternalName services).
	ClusterIp *string `json:"cluster_ip,omitempty"`

	// Labels Arbitrary user-supplied string key/value labels.
	Labels *map[string]string `json:"labels,omitempty"`

	// Name Kubernetes service name (DNS-label style). Unique per namespace.
	// Immutable after creation.
	Name string `json:"name"`

	// NamespaceId Parent namespace id. Immutable after creation; the namespace
	// must already exist or the create returns 404.
	NamespaceId openapi_types.UUID `json:"namespace_id"`

	// Ports Service ports. Opaque in v1: each entry carries whatever the
	// collector chose to persist (name, port, target_port, protocol, node_port).
	Ports *[]map[string]interface{} `json:"ports,omitempty"`

	// Selector Pod label selector. Pods matching every key/value are selected.
	Selector *map[string]string `json:"selector,omitempty"`

	// Type Kubernetes Service type. Casing matches the enum Kubernetes itself
	// emits. Open-ended at the schema layer to accommodate future additions;
	// handler validation enforces the v1 subset.
	Type *ServiceType `json:"type,omitempty"`
}

// ServiceList Paged list of services.
type ServiceList struct {
	Items []Service `json:"items"`

	// NextCursor Opaque cursor to pass as `?cursor=` to fetch the next page.
	// Absent or null when no more pages remain.
	NextCursor *string `json:"next_cursor,omitempty"`
}

// ServiceMutable Fields on a Service that clients may set and later update.
type ServiceMutable struct {
	// ClusterIp Assigned ClusterIP (empty for Headless / ExternalName services).
	ClusterIp *string `json:"cluster_ip,omitempty"`

	// Labels Arbitrary user-supplied string key/value labels.
	Labels *map[string]string `json:"labels,omitempty"`

	// Ports Service ports. Opaque in v1: each entry carries whatever the
	// collector chose to persist (name, port, target_port, protocol, node_port).
	Ports *[]map[string]interface{} `json:"ports,omitempty"`

	// Selector Pod label selector. Pods matching every key/value are selected.
	Selector *map[string]string `json:"selector,omitempty"`

	// Type Kubernetes Service type. Casing matches the enum Kubernetes itself
	// emits. Open-ended at the schema layer to accommodate future additions;
	// handler validation enforces the v1 subset.
	Type *ServiceType `json:"type,omitempty"`
}

// ServiceType Kubernetes Service type. Casing matches the enum Kubernetes itself
// emits. Open-ended at the schema layer to accommodate future additions;
// handler validation enforces the v1 subset.
type ServiceType string

// ServiceUpdate Fields on a Service that clients may set and later update.
type ServiceUpdate = ServiceMutable

// Workload defines model for Workload.
type Workload struct {
	CreatedAt *time.Time          `json:"created_at,omitempty"`
	Id        *openapi_types.UUID `json:"id,omitempty"`

	// Kind Kubernetes workload controller kind. Casing matches the `kind` field
	// Kubernetes itself emits. Additional kinds (Job, CronJob, ReplicaSet,
	// ReplicationController) may be introduced as new enum values without a
	// schema migration (see ADR-0003).
	Kind WorkloadKind `json:"kind"`

	// Labels Arbitrary user-supplied string key/value labels.
	Labels *map[string]string `json:"labels,omitempty"`

	// Layer Always `applicative` for Workload. Set by the server.
	Layer       *Layer             `json:"layer,omitempty"`
	Name        string             `json:"name"`
	NamespaceId openapi_types.UUID `json:"namespace_id"`

	// ReadyReplicas Observed ready replica count. Nullable until first status update.
	ReadyReplicas *int `json:"ready_replicas,omitempty"`

	// Replicas Desired replica count. Nullable; DaemonSet has no scalar desired count.
	Replicas *int `json:"replicas,omitempty"`

	// Spec Kind-specific fields the collector chooses to persist (e.g. strategy
	// for Deployment, service_name for StatefulSet). Open-ended; stored
	// as JSONB.
	Spec      *map[string]interface{} `json:"spec,omitempty"`
	UpdatedAt *time.Time              `json:"updated_at,omitempty"`
}

// WorkloadCreate defines model for WorkloadCreate.
type WorkloadCreate struct {
	// Kind Workload kind discriminator. Immutable after creation.
	Kind WorkloadKind `json:"kind"`

	// Labels Arbitrary user-supplied string key/value labels.
	Labels *map[string]string `json:"labels,omitempty"`

	// Name Kubernetes workload name (DNS-subdomain style). Unique per
	// (namespace, kind). Immutable after creation.
	Name string `json:"name"`

	// NamespaceId Parent namespace id. Immutable after creation; the namespace
	// must already exist or the create returns 404.
	NamespaceId openapi_types.UUID `json:"namespace_id"`

	// ReadyReplicas Observed ready replica count. Nullable until first status update.
	ReadyReplicas *int `json:"ready_replicas,omitempty"`

	// Replicas Desired replica count. Nullable; DaemonSet has no scalar desired count.
	Replicas *int `json:"replicas,omitempty"`

	// Spec Kind-specific fields the collector chooses to persist (e.g. strategy
	// for Deployment, service_name for StatefulSet). Open-ended; stored
	// as JSONB.
	Spec *map[string]interface{} `json:"spec,omitempty"`
}

// WorkloadKind Kubernetes workload controller kind. Casing matches the `kind` field
// Kubernetes itself emits. Additional kinds (Job, CronJob, ReplicaSet,
// ReplicationController) may be introduced as new enum values without a
// schema migration (see ADR-0003).
type WorkloadKind string

// WorkloadList Paged list of workloads.
type WorkloadList struct {
	Items []Workload `json:"items"`

	// NextCursor Opaque cursor to pass as `?cursor=` to fetch the next page.
	// Absent or null when no more pages remain.
	NextCursor *string `json:"next_cursor,omitempty"`
}

// WorkloadMutable Fields on a Workload that clients may set and later update.
type WorkloadMutable struct {
	// Labels Arbitrary user-supplied string key/value labels.
	Labels *map[string]string `json:"labels,omitempty"`

	// ReadyReplicas Observed ready replica count. Nullable until first status update.
	ReadyReplicas *int `json:"ready_replicas,omitempty"`

	// Replicas Desired replica count. Nullable; DaemonSet has no scalar desired count.
	Replicas *int `json:"replicas,omitempty"`

	// Spec Kind-specific fields the collector chooses to persist (e.g. strategy
	// for Deployment, service_name for StatefulSet). Open-ended; stored
	// as JSONB.
	Spec *map[string]interface{} `json:"spec,omitempty"`
}

// WorkloadUpdate Fields on a Workload that clients may set and later update.
type WorkloadUpdate = WorkloadMutable

// ClusterId defines model for ClusterId.
type ClusterId = openapi_types.UUID

// Cursor defines model for Cursor.
type Cursor = string

// IngressId defines model for IngressId.
type IngressId = openapi_types.UUID

// IngressNamespaceIdFilter defines model for IngressNamespaceIdFilter.
type IngressNamespaceIdFilter = openapi_types.UUID

// Limit defines model for Limit.
type Limit = int

// NamespaceClusterIdFilter defines model for NamespaceClusterIdFilter.
type NamespaceClusterIdFilter = openapi_types.UUID

// NamespaceId defines model for NamespaceId.
type NamespaceId = openapi_types.UUID

// NodeClusterIdFilter defines model for NodeClusterIdFilter.
type NodeClusterIdFilter = openapi_types.UUID

// NodeId defines model for NodeId.
type NodeId = openapi_types.UUID

// PodId defines model for PodId.
type PodId = openapi_types.UUID

// PodNamespaceIdFilter defines model for PodNamespaceIdFilter.
type PodNamespaceIdFilter = openapi_types.UUID

// ServiceId defines model for ServiceId.
type ServiceId = openapi_types.UUID

// ServiceNamespaceIdFilter defines model for ServiceNamespaceIdFilter.
type ServiceNamespaceIdFilter = openapi_types.UUID

// WorkloadId defines model for WorkloadId.
type WorkloadId = openapi_types.UUID

// WorkloadKindFilter Kubernetes workload controller kind. Casing matches the `kind` field
// Kubernetes itself emits. Additional kinds (Job, CronJob, ReplicaSet,
// ReplicationController) may be introduced as new enum values without a
// schema migration (see ADR-0003).
type WorkloadKindFilter = WorkloadKind

// WorkloadNamespaceIdFilter defines model for WorkloadNamespaceIdFilter.
type WorkloadNamespaceIdFilter = openapi_types.UUID

// BadRequest RFC 7807 problem details.
type BadRequest = Problem

// Conflict RFC 7807 problem details.
type Conflict = Problem

// Forbidden RFC 7807 problem details.
type Forbidden = Problem

// NotFound RFC 7807 problem details.
type NotFound = Problem

// Unauthorized RFC 7807 problem details.
type Unauthorized = Problem

// ListClustersParams defines parameters for ListClusters.
type ListClustersParams struct {
	// Limit Maximum number of items to return. Server clamps to [1, 200].
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque cursor returned from a previous list response.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// ListIngressesParams defines parameters for ListIngresses.
type ListIngressesParams struct {
	// Limit Maximum number of items to return. Server clamps to [1, 200].
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque cursor returned from a previous list response.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`

	// NamespaceId Return only ingresses belonging to this namespace.
	NamespaceId *IngressNamespaceIdFilter `form:"namespace_id,omitempty" json:"namespace_id,omitempty"`
}

// ListNamespacesParams defines parameters for ListNamespaces.
type ListNamespacesParams struct {
	// Limit Maximum number of items to return. Server clamps to [1, 200].
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque cursor returned from a previous list response.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`

	// ClusterId Return only namespaces belonging to this cluster.
	ClusterId *NamespaceClusterIdFilter `form:"cluster_id,omitempty" json:"cluster_id,omitempty"`
}

// ListNodesParams defines parameters for ListNodes.
type ListNodesParams struct {
	// Limit Maximum number of items to return. Server clamps to [1, 200].
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque cursor returned from a previous list response.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`

	// ClusterId Return only nodes belonging to this cluster.
	ClusterId *NodeClusterIdFilter `form:"cluster_id,omitempty" json:"cluster_id,omitempty"`
}

// ListPodsParams defines parameters for ListPods.
type ListPodsParams struct {
	// Limit Maximum number of items to return. Server clamps to [1, 200].
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque cursor returned from a previous list response.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`

	// NamespaceId Return only pods belonging to this namespace.
	NamespaceId *PodNamespaceIdFilter `form:"namespace_id,omitempty" json:"namespace_id,omitempty"`
}

// ListServicesParams defines parameters for ListServices.
type ListServicesParams struct {
	// Limit Maximum number of items to return. Server clamps to [1, 200].
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque cursor returned from a previous list response.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`

	// NamespaceId Return only services belonging to this namespace.
	NamespaceId *ServiceNamespaceIdFilter `form:"namespace_id,omitempty" json:"namespace_id,omitempty"`
}

// ListWorkloadsParams defines parameters for ListWorkloads.
type ListWorkloadsParams struct {
	// Limit Maximum number of items to return. Server clamps to [1, 200].
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque cursor returned from a previous list response.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`

	// NamespaceId Return only workloads belonging to this namespace.
	NamespaceId *WorkloadNamespaceIdFilter `form:"namespace_id,omitempty" json:"namespace_id,omitempty"`

	// Kind Return only workloads of this kind.
	Kind *WorkloadKindFilter `form:"kind,omitempty" json:"kind,omitempty"`
}

// CreateClusterJSONRequestBody defines body for CreateCluster for application/json ContentType.
type CreateClusterJSONRequestBody = ClusterCreate

// UpdateClusterApplicationMergePatchPlusJSONRequestBody defines body for UpdateCluster for application/merge-patch+json ContentType.
type UpdateClusterApplicationMergePatchPlusJSONRequestBody = ClusterUpdate

// CreateIngressJSONRequestBody defines body for CreateIngress for application/json ContentType.
type CreateIngressJSONRequestBody = IngressCreate

// UpdateIngressApplicationMergePatchPlusJSONRequestBody defines body for UpdateIngress for application/merge-patch+json ContentType.
type UpdateIngressApplicationMergePatchPlusJSONRequestBody = IngressUpdate

// CreateNamespaceJSONRequestBody defines body for CreateNamespace for application/json ContentType.
type CreateNamespaceJSONRequestBody = NamespaceCreate

// UpdateNamespaceApplicationMergePatchPlusJSONRequestBody defines body for UpdateNamespace for application/merge-patch+json ContentType.
type UpdateNamespaceApplicationMergePatchPlusJSONRequestBody = NamespaceUpdate

// CreateNodeJSONRequestBody defines body for CreateNode for application/json ContentType.
type CreateNodeJSONRequestBody = NodeCreate

// UpdateNodeApplicationMergePatchPlusJSONRequestBody defines body for UpdateNode for application/merge-patch+json ContentType.
type UpdateNodeApplicationMergePatchPlusJSONRequestBody = NodeUpdate

// CreatePodJSONRequestBody defines body for CreatePod for application/json ContentType.
type CreatePodJSONRequestBody = PodCreate

// UpdatePodApplicationMergePatchPlusJSONRequestBody defines body for UpdatePod for application/merge-patch+json ContentType.
type UpdatePodApplicationMergePatchPlusJSONRequestBody = PodUpdate

// CreateServiceJSONRequestBody defines body for CreateService for application/json ContentType.
type CreateServiceJSONRequestBody = ServiceCreate

// UpdateServiceApplicationMergePatchPlusJSONRequestBody defines body for UpdateService for application/merge-patch+json ContentType.
type UpdateServiceApplicationMergePatchPlusJSONRequestBody = ServiceUpdate

// CreateWorkloadJSONRequestBody defines body for CreateWorkload for application/json ContentType.
type CreateWorkloadJSONRequestBody = WorkloadCreate

// UpdateWorkloadApplicationMergePatchPlusJSONRequestBody defines body for UpdateWorkload for application/merge-patch+json ContentType.
type UpdateWorkloadApplicationMergePatchPlusJSONRequestBody = WorkloadUpdate

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Liveness probe
	// (GET /healthz)
	GetHealthz(w http.ResponseWriter, r *http.Request)
	// Readiness probe
	// (GET /readyz)
	GetReadyz(w http.ResponseWriter, r *http.Request)
	// List clusters
	// (GET /v1/clusters)
	ListClusters(w http.ResponseWriter, r *http.Request, params ListClustersParams)
	// Register a cluster
	// (POST /v1/clusters)
	CreateCluster(w http.ResponseWriter, r *http.Request)
	// Delete a cluster
	// (DELETE /v1/clusters/{id})
	DeleteCluster(w http.ResponseWriter, r *http.Request, id ClusterId)
	// Get a cluster
	// (GET /v1/clusters/{id})
	GetCluster(w http.ResponseWriter, r *http.Request, id ClusterId)
	// Update mutable fields of a cluster
	// (PATCH /v1/clusters/{id})
	UpdateCluster(w http.ResponseWriter, r *http.Request, id ClusterId)
	// List ingresses
	// (GET /v1/ingresses)
	ListIngresses(w http.ResponseWriter, r *http.Request, params ListIngressesParams)
	// Register an ingress
	// (POST /v1/ingresses)
	CreateIngress(w http.ResponseWriter, r *http.Request)
	// Delete an ingress
	// (DELETE /v1/ingresses/{id})
	DeleteIngress(w http.ResponseWriter, r *http.Request, id IngressId)
	// Get an ingress
	// (GET /v1/ingresses/{id})
	GetIngress(w http.ResponseWriter, r *http.Request, id IngressId)
	// Update mutable fields of an ingress
	// (PATCH /v1/ingresses/{id})
	UpdateIngress(w http.ResponseWriter, r *http.Request, id IngressId)
	// List namespaces
	// (GET /v1/namespaces)
	ListNamespaces(w http.ResponseWriter, r *http.Request, params ListNamespacesParams)
	// Register a namespace
	// (POST /v1/namespaces)
	CreateNamespace(w http.ResponseWriter, r *http.Request)
	// Delete a namespace
	// (DELETE /v1/namespaces/{id})
	DeleteNamespace(w http.ResponseWriter, r *http.Request, id NamespaceId)
	// Get a namespace
	// (GET /v1/namespaces/{id})
	GetNamespace(w http.ResponseWriter, r *http.Request, id NamespaceId)
	// Update mutable fields of a namespace
	// (PATCH /v1/namespaces/{id})
	UpdateNamespace(w http.ResponseWriter, r *http.Request, id NamespaceId)
	// List nodes
	// (GET /v1/nodes)
	ListNodes(w http.ResponseWriter, r *http.Request, params ListNodesParams)
	// Register a node
	// (POST /v1/nodes)
	CreateNode(w http.ResponseWriter, r *http.Request)
	// Delete a node
	// (DELETE /v1/nodes/{id})
	DeleteNode(w http.ResponseWriter, r *http.Request, id NodeId)
	// Get a node
	// (GET /v1/nodes/{id})
	GetNode(w http.ResponseWriter, r *http.Request, id NodeId)
	// Update mutable fields of a node
	// (PATCH /v1/nodes/{id})
	UpdateNode(w http.ResponseWriter, r *http.Request, id NodeId)
	// List pods
	// (GET /v1/pods)
	ListPods(w http.ResponseWriter, r *http.Request, params ListPodsParams)
	// Register a pod
	// (POST /v1/pods)
	CreatePod(w http.ResponseWriter, r *http.Request)
	// Delete a pod
	// (DELETE /v1/pods/{id})
	DeletePod(w http.ResponseWriter, r *http.Request, id PodId)
	// Get a pod
	// (GET /v1/pods/{id})
	GetPod(w http.ResponseWriter, r *http.Request, id PodId)
	// Update mutable fields of a pod
	// (PATCH /v1/pods/{id})
	UpdatePod(w http.ResponseWriter, r *http.Request, id PodId)
	// List services
	// (GET /v1/services)
	ListServices(w http.ResponseWriter, r *http.Request, params ListServicesParams)
	// Register a service
	// (POST /v1/services)
	CreateService(w http.ResponseWriter, r *http.Request)
	// Delete a service
	// (DELETE /v1/services/{id})
	DeleteService(w http.ResponseWriter, r *http.Request, id ServiceId)
	// Get a service
	// (GET /v1/services/{id})
	GetService(w http.ResponseWriter, r *http.Request, id ServiceId)
	// Update mutable fields of a service
	// (PATCH /v1/services/{id})
	UpdateService(w http.ResponseWriter, r *http.Request, id ServiceId)
	// List workloads
	// (GET /v1/workloads)
	ListWorkloads(w http.ResponseWriter, r *http.Request, params ListWorkloadsParams)
	// Register a workload
	// (POST /v1/workloads)
	CreateWorkload(w http.ResponseWriter, r *http.Request)
	// Delete a workload
	// (DELETE /v1/workloads/{id})
	DeleteWorkload(w http.ResponseWriter, r *http.Request, id WorkloadId)
	// Get a workload
	// (GET /v1/workloads/{id})
	GetWorkload(w http.ResponseWriter, r *http.Request, id WorkloadId)
	// Update mutable fields of a workload
	// (PATCH /v1/workloads/{id})
	UpdateWorkload(w http.ResponseWriter, r *http.Request, id WorkloadId)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHealthz operation middleware
func (siw *ServerInterfaceWrapper) GetHealthz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealthz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetReadyz operation middleware
func (siw *ServerInterfaceWrapper) GetReadyz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetReadyz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListClusters operation middleware
func (siw *ServerInterfaceWrapper) ListClusters(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"read"})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListClustersParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListClusters(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateCluster operation middleware
func (siw *ServerInterfaceWrapper) CreateCluster(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"write"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateCluster(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteCluster operation middleware
func (siw *ServerInterfaceWrapper) DeleteCluster(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ClusterId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"delete"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteCluster(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCluster operation middleware
func (siw *ServerInterfaceWrapper) GetCluster(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ClusterId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"read"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCluster(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateCluster operation middleware
func (siw *ServerInterfaceWrapper) UpdateCluster(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ClusterId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"write"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateCluster(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListIngresses operation middleware
func (siw *ServerInterfaceWrapper) ListIngresses(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"read"})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListIngressesParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		return
	}

	// ------------- Optional query parameter "namespace_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "namespace_id", r.URL.Query(), &params.NamespaceId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "namespace_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListIngresses(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateIngress operation middleware
func (siw *ServerInterfaceWrapper) CreateIngress(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"write"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateIngress(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteIngress operation middleware
func (siw *ServerInterfaceWrapper) DeleteIngress(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IngressId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"delete"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteIngress(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetIngress operation middleware
func (siw *ServerInterfaceWrapper) GetIngress(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IngressId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"read"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetIngress(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateIngress operation middleware
func (siw *ServerInterfaceWrapper) UpdateIngress(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IngressId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"write"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateIngress(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListNamespaces operation middleware
func (siw *ServerInterfaceWrapper) ListNamespaces(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"read"})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListNamespacesParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		return
	}

	// ------------- Optional query parameter "cluster_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cluster_id", r.URL.Query(), &params.ClusterId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cluster_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListNamespaces(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateNamespace operation middleware
func (siw *ServerInterfaceWrapper) CreateNamespace(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"write"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateNamespace(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteNamespace operation middleware
func (siw *ServerInterfaceWrapper) DeleteNamespace(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id NamespaceId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"delete"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteNamespace(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetNamespace operation middleware
func (siw *ServerInterfaceWrapper) GetNamespace(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id NamespaceId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"read"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetNamespace(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateNamespace operation middleware
func (siw *ServerInterfaceWrapper) UpdateNamespace(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id NamespaceId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"write"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateNamespace(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListNodes operation middleware
func (siw *ServerInterfaceWrapper) ListNodes(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"read"})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListNodesParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		return
	}

	// ------------- Optional query parameter "cluster_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cluster_id", r.URL.Query(), &params.ClusterId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cluster_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListNodes(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateNode operation middleware
func (siw *ServerInterfaceWrapper) CreateNode(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"write"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateNode(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteNode operation middleware
func (siw *ServerInterfaceWrapper) DeleteNode(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id NodeId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"delete"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteNode(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetNode operation middleware
func (siw *ServerInterfaceWrapper) GetNode(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id NodeId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"read"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetNode(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateNode operation middleware
func (siw *ServerInterfaceWrapper) UpdateNode(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id NodeId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"write"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateNode(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListPods operation middleware
func (siw *ServerInterfaceWrapper) ListPods(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"read"})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListPodsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		return
	}

	// ------------- Optional query parameter "namespace_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "namespace_id", r.URL.Query(), &params.NamespaceId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "namespace_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListPods(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreatePod operation middleware
func (siw *ServerInterfaceWrapper) CreatePod(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"write"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreatePod(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeletePod operation middleware
func (siw *ServerInterfaceWrapper) DeletePod(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id PodId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"delete"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeletePod(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPod operation middleware
func (siw *ServerInterfaceWrapper) GetPod(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id PodId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"read"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPod(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdatePod operation middleware
func (siw *ServerInterfaceWrapper) UpdatePod(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id PodId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"write"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdatePod(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListServices operation middleware
func (siw *ServerInterfaceWrapper) ListServices(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"read"})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListServicesParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		return
	}

	// ------------- Optional query parameter "namespace_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "namespace_id", r.URL.Query(), &params.NamespaceId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "namespace_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListServices(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateService operation middleware
func (siw *ServerInterfaceWrapper) CreateService(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"write"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateService(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteService operation middleware
func (siw *ServerInterfaceWrapper) DeleteService(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ServiceId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"delete"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteService(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetService operation middleware
func (siw *ServerInterfaceWrapper) GetService(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ServiceId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"read"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetService(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateService operation middleware
func (siw *ServerInterfaceWrapper) UpdateService(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ServiceId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"write"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateService(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListWorkloads operation middleware
func (siw *ServerInterfaceWrapper) ListWorkloads(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"read"})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListWorkloadsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		return
	}

	// ------------- Optional query parameter "namespace_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "namespace_id", r.URL.Query(), &params.NamespaceId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "namespace_id", Err: err})
		return
	}

	// ------------- Optional query parameter "kind" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "kind", r.URL.Query(), &params.Kind, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "kind", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListWorkloads(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateWorkload operation middleware
func (siw *ServerInterfaceWrapper) CreateWorkload(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"write"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateWorkload(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteWorkload operation middleware
func (siw *ServerInterfaceWrapper) DeleteWorkload(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id WorkloadId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"delete"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteWorkload(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetWorkload operation middleware
func (siw *ServerInterfaceWrapper) GetWorkload(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id WorkloadId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"read"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetWorkload(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateWorkload operation middleware
func (siw *ServerInterfaceWrapper) UpdateWorkload(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id WorkloadId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"write"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateWorkload(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/healthz", wrapper.GetHealthz)
	m.HandleFunc("GET "+options.BaseURL+"/readyz", wrapper.GetReadyz)
	m.HandleFunc("GET "+options.BaseURL+"/v1/clusters", wrapper.ListClusters)
	m.HandleFunc("POST "+options.BaseURL+"/v1/clusters", wrapper.CreateCluster)
	m.HandleFunc("DELETE "+options.BaseURL+"/v1/clusters/{id}", wrapper.DeleteCluster)
	m.HandleFunc("GET "+options.BaseURL+"/v1/clusters/{id}", wrapper.GetCluster)
	m.HandleFunc("PATCH "+options.BaseURL+"/v1/clusters/{id}", wrapper.UpdateCluster)
	m.HandleFunc("GET "+options.BaseURL+"/v1/ingresses", wrapper.ListIngresses)
	m.HandleFunc("POST "+options.BaseURL+"/v1/ingresses", wrapper.CreateIngress)
	m.HandleFunc("DELETE "+options.BaseURL+"/v1/ingresses/{id}", wrapper.DeleteIngress)
	m.HandleFunc("GET "+options.BaseURL+"/v1/ingresses/{id}", wrapper.GetIngress)
	m.HandleFunc("PATCH "+options.BaseURL+"/v1/ingresses/{id}", wrapper.UpdateIngress)
	m.HandleFunc("GET "+options.BaseURL+"/v1/namespaces", wrapper.ListNamespaces)
	m.HandleFunc("POST "+options.BaseURL+"/v1/namespaces", wrapper.CreateNamespace)
	m.HandleFunc("DELETE "+options.BaseURL+"/v1/namespaces/{id}", wrapper.DeleteNamespace)
	m.HandleFunc("GET "+options.BaseURL+"/v1/namespaces/{id}", wrapper.GetNamespace)
	m.HandleFunc("PATCH "+options.BaseURL+"/v1/namespaces/{id}", wrapper.UpdateNamespace)
	m.HandleFunc("GET "+options.BaseURL+"/v1/nodes", wrapper.ListNodes)
	m.HandleFunc("POST "+options.BaseURL+"/v1/nodes", wrapper.CreateNode)
	m.HandleFunc("DELETE "+options.BaseURL+"/v1/nodes/{id}", wrapper.DeleteNode)
	m.HandleFunc("GET "+options.BaseURL+"/v1/nodes/{id}", wrapper.GetNode)
	m.HandleFunc("PATCH "+options.BaseURL+"/v1/nodes/{id}", wrapper.UpdateNode)
	m.HandleFunc("GET "+options.BaseURL+"/v1/pods", wrapper.ListPods)
	m.HandleFunc("POST "+options.BaseURL+"/v1/pods", wrapper.CreatePod)
	m.HandleFunc("DELETE "+options.BaseURL+"/v1/pods/{id}", wrapper.DeletePod)
	m.HandleFunc("GET "+options.BaseURL+"/v1/pods/{id}", wrapper.GetPod)
	m.HandleFunc("PATCH "+options.BaseURL+"/v1/pods/{id}", wrapper.UpdatePod)
	m.HandleFunc("GET "+options.BaseURL+"/v1/services", wrapper.ListServices)
	m.HandleFunc("POST "+options.BaseURL+"/v1/services", wrapper.CreateService)
	m.HandleFunc("DELETE "+options.BaseURL+"/v1/services/{id}", wrapper.DeleteService)
	m.HandleFunc("GET "+options.BaseURL+"/v1/services/{id}", wrapper.GetService)
	m.HandleFunc("PATCH "+options.BaseURL+"/v1/services/{id}", wrapper.UpdateService)
	m.HandleFunc("GET "+options.BaseURL+"/v1/workloads", wrapper.ListWorkloads)
	m.HandleFunc("POST "+options.BaseURL+"/v1/workloads", wrapper.CreateWorkload)
	m.HandleFunc("DELETE "+options.BaseURL+"/v1/workloads/{id}", wrapper.DeleteWorkload)
	m.HandleFunc("GET "+options.BaseURL+"/v1/workloads/{id}", wrapper.GetWorkload)
	m.HandleFunc("PATCH "+options.BaseURL+"/v1/workloads/{id}", wrapper.UpdateWorkload)

	return m
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+yd73LbOJLAXwXF26q1ZylZcZzsjlNXWxlns+OdTKKKk9sPUc6GiJaENQlwANCOJuWq",
	"e4h7wnuSqwYI/pEokfIfbWL7S2JJIAB2Nxq/BsDm1yCSSSoFCKODw69BShVNwICyn47iTBtQxww/MNCR",
	"4qnhUgSHwQmoC1A9qjWfCmAkckUJZyAMn3BQ/SAMOBZNqZkFYSBoAsFhwFkQBgp+y7gCFhwalUEY6GgG",
	"CcVWJlIl1ASHQZbZkmae4lXaKC6mwdVVGBxlSku13KN3Kf0tAxLZn4kCkyns2ETJhFCSKrjgMtMk5toQ",
	"BTqVQkPRx98yUPOyk66SoNqxhH55A2JqZsHhsyf7TR07FlMFWneRFndFtyCtvFNvaQI6pREcs9c8NtAg",
	"v/dWYkSKeO77B5qMIZZiysWUGEnMjGsifFWrhFcUOLV92qS3b3jCzXLXfqVfeJIlRGTJGBSRE8INJBq7",
	"5PTcJ07CJIppktofPj0Jyf5g8HlVL2PbVLV7DCY0i01w+GwQorqxyeBwf4CfuHCfnhS95sLAFJTtdiHd",
	"YsB0EXIhpyYp5+NppYG6nzeXcMUQ2s206OEWDPWtZBuKT7LtSk6ybkKTbBvyGkrWpTepZNvpzIYeJpVs",
	"284FRcO7Gb52RbcgubxTG0ov79+2JfhPqc5jSTsZ3mVedgsy9N36hYtO0vNd0ziTWKGdc8FWyQt/q8np",
	"DwomwWHwH3slOu25X/VetSu1vm2o4LKL29TwFerBkZHlv58oew+/ZaDtnBxJYUDYP2maxjyi2PG9VMlx",
	"DMmf/qXxLr52FNTQXeUaXZztY+woMKJc4/0AsU+KScyjrfbEt0kuuZkhWSoQhmhDDZAd6E/7IWGZax+s",
	"WnZtV19LNeaMgdhmXz/IcxCEa3JBY87IODMkptG5JmYGREcyBeLHGBnP7bcyBWV7Y3v9VprXMhNsm51+",
	"D1pmKgIipCETbN125aOgmZlJxX+HrXbnV641jjSpCBe5HIEqUMSgdPt2ROf1VOIj2684fjcJDj+tbzu/",
	"4NfM0HEMwVX4NUgVqsFwN+IiBdQAO6WmNl4ZNdAzPAHrKSl7J+K595QLgzhEf9ow1lsvi+l8k1t5Y4tf",
	"fV6U4cv4ks41OeNioqg2KotMpuA0llMe0fiMTKQiuRiQ2o03Rm3nj/5ST6+8W6uFYM8PLJT7j/shzikG",
	"FPbgvz/R3u+D3o+f8/97n78Owuf7V/7rPwQNd5+l7IaCv6pOYp/crGZ77kUbVrVba/FzUZkc/wsi0yRW",
	"8ks2BiXAQIG4RMGU4x82orRSPPr11U/OXboiR7bFWzRQr4uFyd8WJzrOpr2Yn1fBKSSZ4BiY00hJrcte",
	"jsRxkrh2CJ3g7VjxoDsaiSC8Q20vaMreUgcVDOncAo2NOp3gCSUCLsuQoxT8G64bAtkhnQJzSxBy4i/T",
	"aPR1KdvwtvZHB6Vh6/k9UKXoHD8L+GJOo04rJkaSlGpNqCZnf3Xf/ecZfjsBE82s3rA2ktIp9Efi5Vjj",
	"ZCgVEVkck8sZCCIkSaQCW0QTBQnluTKxjLWobmPH3vWySgrpevtcuqXXHGLkOkGo9zLEzKghUcxRZiSh",
	"SM+GUMFITPFnNw6XdUBTfgqCpZKLBk1WRuPL4XHuvcjH92/IDhfOfXApaLyLFZe+WPEm58O4TmM6P20e",
	"XD9nCRW9ieIgWDwnMR1DHJKJAuhhxf36WNl/9ryhBRAXXEmRQNO9vPZVkUoxYui0gBy4CBF7EENDkirJ",
	"dvvLI3Sp0fNCRqcXoDR3s/QCYuVKqggxL0sUpFIZhysVcds+kVHwpL//Y//ZKFjsytP9xsltDLFTK2Pc",
	"qWZYU3erCBf8sRpzo6iak0yD6ukMuQQjR1uenMN874LGGTh16byP1SYrIivtO1XygrOm6OCjYKDiOVZe",
	"EQbj2OA4w0I4FmdSGyzi6+mPxLsURA8EA/aCRDJJpCC2Z/qQTM8hJHCuQ0LxH5mC0DM+MSFR+Avqj7Ik",
	"JFKkCvB/M7NVdtA9ekin7/Ulr1YP8o92YF5/7lpy4L+CmkIvpejOxpLN+wSnc+InoYn1HS/IGQ7DM0Rp",
	"7icoFGPCDRqjK0WoAhLDxJBMRDMqpsBQLldh8DPQGO91ceLEqCGzf4HIEvRy8rzi4krJrRwqP2U8ZsXo",
	"sKErEJUJgQqnaiq1jWHXu9a8G02+NV8q7i7w/IKHQLNF2HEBDmHze0eEBfLy1fveYDA46EyvT2s886SR",
	"Z3Y+9fK/fvBf7f61kV1r8X57mH+XsFtZdrgj9s0Fv4598yKbsm+rOTdPz5W++W0dLEh2Xr096VnvT7SZ",
	"x7DbJx8dCaegKos4m3Dw3drNIqva1Y7qHkCfrOrqC8eHvuxIJJk2hMZoRnMCXyzxKlvIGUK+caPJweDA",
	"3Wf7Ot8itC8a240Y3usuw3kWvytX2UqT6kL1xd7ZTbHe++MHgPULQ28d1ovCA1yT63P9nEYx1XoFcnsP",
	"gkXcaLaWK4VRMo5BkTEXzG4z5oQ8CsSUiy+jAP80isKEny+j6f6zp98xm6osdt1plBVRMrPoaYv1SW6F",
	"XJCLJ4cEaDQjIIyak4gqxUGTyxk1cGHjMxiJCOUaGalINJMarNki6WhDdhBqQ5JSM3P/nmLXQjKm0TmI",
	"YrNmJKyi9ghGDbvOPotx1izZmtGWN7o42kzccNsf3pygQUz4NHOLqPb2eKdbxxvSI4G2ahkOJqBARMDI",
	"CUQKnNO9vTu4Wj3iNmXsxTnyRozt/feZHbU5dlMFI1GCN+nK3W888C2MhbcnJ8coeCOniqYzjJ/nzugI",
	"1egx3AYLDuYazO1bzLO2ec4F6xnZc1cmNE0tcXvt5ZE+kDHMeP6l5l98cckgdrr04A+R1HNtIAnCYJxp",
	"LtDLh0GFMfETS7jA6M5Wb3d6mhZUl39IZ3Ntf2kKLoptqO4qLy5Zw/nlnnoX/HwYi9yF3G6yzH27wHc3",
	"3F87UXFH1F9S6BruL4/hbEj+G5t4IymXR+DaONmXREgeiduk5LA9SClF2SFM8Svb/64gZcHelk3tRsxf",
	"isJTf3Ulv7CKLtRfHua6KfaXLvoBgP/SyFu7ol+Uvi773/1C+3ez0DyjuqufsGXRjmKKxj62cxgrFuJf",
	"RogsLvT5ACrhgmIggOFPdfUZTY9GdgUalUOomJNSRq4RTWqrKUZJluGQWvQxT/c7LSQX9rIp5i5PCNcG",
	"3dJl3QrmvpVsk/uQ7BHbWrHNE3PObZLdBNlsjN+6WV3Mf/37DG2Srec1yTZHtQ0s+rumNJRdCWg6GzOJ",
	"0+8tQdotW+kdYxrKopHQJOsGZ5LdApeh530ISFYZYetpDNVy3cMVKppxA9b/NhwKGH4k1RJ9smYTmybs",
	"+UFIqErwvzSNnh/EEBL99MfBly7gsI3jF+fZGGIwq49B/OIKkCk3xQ4v1W1HIC7u5RkIqU95QqcNqrAW",
	"9+6E2J99M14YH8eZMBnZ3+8PDvpPyZsPJ00L8M+7gaNkmzNjdWb6VnBxKFn3OxhK9iD38oeS3SLwPbkp",
	"8D2o7fxUsnWIOJRsU0Jca8Wt3IX96Yhd19rCv3NredCb+Ki95g38oWRdSDGV7MagiD73AXBiZZytxcSh",
	"ZNelxO+FWDC+WEGPb9GX5Gf1hANmcA9laoIGw7IYGJGi00mB9kU7rLl5ue6QDEEwe4D3vTszGJKTLIoA",
	"GLBwJF5THgML0Yo+inMhL0WVujst3nWj7VSyU542DETJyPEQa7XHCXaOhxcH2Jvj4cXz3T45rp6qfmEf",
	"GLJP6ODEgzdLxUgcD0nMDSgaL3Xl4Fkn8BtKtin3Veebb2c73D/ltPyU4esj8ue/DP5M8qenCANDedzg",
	"9dwP+NfycXKlpNIrxn0vhguIvXbsyQhbPHSeKccvvJvq+YZ62/b2GptOQOs8OFjvuVwV5QWfO5z04EIb",
	"KtzueNuh/fJAb5Er4NmPP1ZzBQwGy9kCwsBwE0PjrbkvKokIAjqWmTkcx1Sctz5GsHD79lffWrju3G/+",
	"CHJ3i88veJCxQn7v386e/oOKFnLpr4sY8iKbRg2tNt0aOficAY+Hf7+/uMHrrjl2yG2jS/zgEzPcNIbw",
	"PvkBxBELI29tLOHH/zXjiWJxrQE/X/rEFT4JzZDsQJKauXX7PwNlMWLpHvnbFxx0NLZk7/W9uNDYgJvf",
	"0dkAqYxuzvCBwrc/3+oBXxxuoa03JIaqKZhT9yFV0shIxqGNnU5v/WSvBtenW9QJhjG5488r72MIjGZq",
	"ohmqBWUyrygHGd6VBdZVRR4VO/iQD1i0MdipFlg3sxWjbp5CnxxRmyPB3g6457lBZEnt5IbREE9GAhLu",
	"LKUII6nJ81FgF/1R3HpoOclMpqCILvWLkZhRwWJQtZACw8Eob//iCdHZWIOpn7MtRnLgVvSHUiF/vJGU",
	"/URj5Hxkk+p4bjwzm9/+pnHhIlF8O7Ghz0nT/V78Fd8k8tsEPRvl5bn7MMG397iv0BYp5OmV7ihgKLJQ",
	"VZ7dWRM8eLVtGj20jw9vpJvV58x16Rb9zzZvFWEcf7PH7nCyWRdQdDl5Uois2zbISOwUGg1th3bX9+Fx",
	"O6RjWFMdGTeKbgqNNoc3NWPrZBmVwWQzpzUxwRn+cubmopFYggOSs8HLchH53D5Tt/MPOQ7JkZLC/vEe",
	"rGc9AROORP4Byx8VXdi1AcAYyvOidj0Yb9xyiTsnYlN4ycwQOhI5fSR8mj+5taPL536e7tYh4hWksZzb",
	"xBlhcGKogUkWnwB+ekUhkQL/bsIGL9YuYWOR7u2mcWMxtT+AwHHR6a6NHAuXec+3oqxzOlVuoDQEce/8",
	"6W3nxfKCJJKZMH3yNlcNyYThMZlwpV2+u0xXJFOscDeub69u+xVom35uRaMvSDGgyAxHsCQ6ojFVhOUX",
	"ugtae6BTiNpCwwUnxwXr4WV8wiPPz+6R30rUKjXoWtxqTx7ZR/RgOh9hREJKdxH6xQG7M+gWj0v3sVs/",
	"06aNVMBGgmryj5N3b39yI2VBu1drBsGm0ckSsdxOeBLmfj/EITUSZaBCNo5TbHgeZYqb+Ql2Ok9JafPx",
	"vcxcihWXne+1n2Vtlr5gaaQNj13+PsK1zoARmZmenPTGVFg+F3a+OHuZpxy0U8IhcQ2RUTYYPI3s5fZP",
	"OOuPxEicRDIFTaaKCpPvjro2DkeCkB45w+F1Rgj5v//5X+fl0cVMwZRJF3Ve8lJxA2euZM4RWNYNN7LD",
	"E/QL2teYB9ARxanvj9rBH2B9u3l9DGLACrE+BYm8QC5xaRZ9k/bZ0rxJGsd+f5qO5QW8wNLORaDJFtF4",
	"wkXPpib1ObE0ysFmndR2ycemJrIzf169Szpp+x9xE8+JpobrydxuHtczUo7EGL+uZKS09m+NFe3d6bkc",
	"ETNjUpfAkYuJbNjk/NvJB5tSCm/hhx9eqqnUP/wQEmpR335bIZJK1itNaJznr+Vm5lau3CPEJxC9zZKj",
	"WGaM7Jy8Pdolv2U0Rn/hGGKiaAI4j1v7+DDjujjIuTPoP+kPdgnXhJJLGp+jpPQ56kkKEskLQJefW84b",
	"fgECcO4Vzknbx4Ptbm2hv3xh46xQLDl6//GVtctsrOG3DGfjvHUknzgmlDF7YDcsH6IKi0kxJEPJ7JB1",
	"KZ5qvAbCcDPP6SyhaWrPK9hktEBWPF6trRD+Zrd9yUTGsbwkxcbzztmqJJ5nOXvpLEmomtfosxfZ5+sj",
	"p8FFLZFlJZUKKbZBcdadSu2qeDk8DirZlgKrJHv+NAVBUx4cBk/tVzYkmVnvszez2Z1+x7+nYLGuMNlj",
	"FhwGfwfzc15kIZfu/mCwJpXpZilM8xxTDRlM/VIdt4Z8Af2aHw0OP32uSrewNWtdKCY61Qhd7jaDz3jx",
	"niWF6i3Xm/wvUHyCHorJS6GNApoQBilObCLC73cYNXRMNexaV6+ARjO//b8kvfeusX+38BwdGenWbIhR",
	"dDLhkQ2Xng2ebjMnbaVTQhrXsfVafV93GqvUevFkzyegXGnOGLsc+UJh7e0gK/iiLLLnXuZwFbYWzN/o",
	"gQhyZ1qvpuVskPKqxJxXYXDgetFUedHbvUqmbHvJk/ZLakmO7UVP2y8qU0svWECdjD7ZOCD4fLUw3HXx",
	"/JOumEXx1We7+aMbDMEtiPlEoy5CA21+kmx+2yrK196u6oFgvk66YB9Pbrvxxizg+XNg+Zokuq0ZUJaP",
	"mzfStdeQsfH9cXHyDy7jua+g+oaKptzsjYd7rr5hS8Qrfmy/osjg3mK6FogXbfd9uaQVFVbYYMALnm3v",
	"K2dXTjVIxcuG/cp+XzXsmoEdrM5Y6mpk/a2K+aD9iiKPe4uYc4ksyNnJo03K4Ur6WSnJwTaHanGm8TvV",
	"TZP3/juYdrVsNkOX7/fCpmyo3/Dypco6gIaECsMjfeiDd+ljeSUT6+rGks0t51Wj+YaUqo07A3Vzcmsa",
	"m046SdnfP13LsPKllE4T0Fas2nWI1R59/ZbnglscCI1zgZPHwkoUTrXd5oYiQeNa7D0uSt0597aXXPkW",
	"tztl5mrSy1ZmrqS9vH/QzCvG4A2r/K4Nm30iz7vB5nq22y1jc5GjdNk8fF7IW8PmXOD3Cps3cpXb5Wzh",
	"Bb7C5he9aUfUrg6GNtT2JnS/UbtN0Kthe6UsB9sc4PcWttsVsxkYlC+I3QZurzoyeA0E33QCuz6C19PS",
	"bhnB19i6R/BiDnpE8BUI3nHaKPMlrqXwt2WxbwDDV77n904xvJ6HshXEq5ko7x+Ji6pBePuqfNnG4mV2",
	"zbuh8cUctFvm8Ury0GU7KdNn3hqT195F+kjlW1j9FhUDbrT/JQfbEczrI6MNzUtbuufr4K3yXo3nayQ6",
	"2PaIv78r4h0UtBk4VF+Rf9egvjrd1zUwffO57fqgvphad8uovtbqPazXj7k/4nrjinnn+USyNla3Jb4F",
	"TJdsy4Tu85C2w7nLRHoPuTxXfmFC9nMrjUt2ZyBeJhfeNoPbRLENk7Fkt0nekj1C99ag29nponFXXWNX",
	"yvYW3wrYaC33na2bxbqGqBulN9jO0L3HCL1KDxuCs2TfHzNvMgPdAJfLhMLbJuUVJl1Asp1HHvl4JR+v",
	"df2pZOuheIgFvgEmHkq25dMjPuNqKxO7nKv3D4lTp3pvOfZjGxAPJbsjHi4zKW8Zh2063KvGPDm3BsOp",
	"ZI8svCUWTq2JLlh1xR12BGFv6W0cjHZyzzG4UaKrIbhRcoNtjNf7S8ArVLDZtD2U7Ps727HJjHN9/i3z",
	"Km8Zf1dYs6dfO3E8wu8q+F3n633qw7X4e+ILfQMInPdlyxhcTR7aisJl+tD7h8O6NAVvUMVXbVjs06He",
	"DRrXUwZvGY+LTK+rH/29NUzO5f2IyltCZV2YbYPFL7jRjthcHQlt6Ozt557j81opr8bolZIcbHNs31+k",
	"blHLZjiQi+v7w+tNZ67rI3Y9Te2WMXuNpXvULiafR9xehdtd5osiVeBa7v5nUeobAG/fmQby7n7xL1xs",
	"hddraRtbgb2SuPH+EftlxYi8QZbftTF7kYrybqB9IVXvlqm9zLO5bCFFqslb43Yv9Edw3xK4X5a222T4",
	"i664I7vXRkQbvBdWdM/pvUXUq/l9tTQH2x3m9xfhW3WzGVp4iW2b4mtJSW+G8xtPatfn+YXMrlsG+nWW",
	"74m+nJYekX4V0rfNJGtbc83Yt0a4AVbXA5JETBhcQCzTPEN5puI8P+rh3l6MBWZSm8O/DP4ysIMu78RS",
	"VeuyjpKdzCoBcCii5u3bjtyLBHxOQST5lYnjfQ6Wla9eKGorsrWsrc8ewiE7KEhQZM/no++lMRVAEhrN",
	"sPu7NjsoF2VamEpD7hzP+laKU/BrKyrPyq+tLZVM24S7NtOukQmPSOW1IdUk/dzoSgN212Vt1Q15+TXZ",
	"qWairiSeDsss27v9kXhJNBfTuMh0zaUgqYzniVTpjEdEimo2/9qrJl6Qatr8PLe763Np4ms77neHSvnW",
	"nifMKyti4LV1Ffl6+uQoplrzCS+trP6CFvfaoRSU7/zBi5HAYqPgckbNHzXhwth6e/AllRrYX0cBoRnj",
	"hljnhULiOFb0pbXlC07zRMkjAZHUc20g6blmFMQu3fOMpzp0763l/tVHCSRjUPhTTXzl89JXn6/+PwAA",
	"///mJJsWo7cAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
