//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for HealthStatus.
const (
	Ok HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Cluster defines model for Cluster.
type Cluster struct {
	// ApiEndpoint Kubernetes API server URL (informational).
	ApiEndpoint *string    `json:"api_endpoint,omitempty"`
	CreatedAt   *time.Time `json:"created_at,omitempty"`

	// DisplayName Human-friendly label, free-form.
	DisplayName *string `json:"display_name,omitempty"`

	// Environment Free-form environment tag (e.g., dev, staging, prod).
	Environment *string             `json:"environment,omitempty"`
	Id          *openapi_types.UUID `json:"id,omitempty"`

	// KubernetesVersion Cluster API server version reported by Kubernetes (e.g. "1.29.5").
	KubernetesVersion *string `json:"kubernetes_version,omitempty"`

	// Labels Arbitrary user-supplied string key/value labels.
	Labels *map[string]string `json:"labels,omitempty"`
	Name   string             `json:"name"`

	// Provider Underlying Kubernetes distribution or hosting provider.
	// Open-ended; common values: gke, eks, aks, openshift, rke, kubeadm, onprem, other.
	Provider  *string    `json:"provider,omitempty"`
	Region    *string    `json:"region,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// ClusterCreate defines model for ClusterCreate.
type ClusterCreate struct {
	// ApiEndpoint Kubernetes API server URL (informational).
	ApiEndpoint *string `json:"api_endpoint,omitempty"`

	// DisplayName Human-friendly label, free-form.
	DisplayName *string `json:"display_name,omitempty"`

	// Environment Free-form environment tag (e.g., dev, staging, prod).
	Environment *string `json:"environment,omitempty"`

	// KubernetesVersion Cluster API server version reported by Kubernetes (e.g. "1.29.5").
	KubernetesVersion *string `json:"kubernetes_version,omitempty"`

	// Labels Arbitrary user-supplied string key/value labels.
	Labels *map[string]string `json:"labels,omitempty"`

	// Name Stable slug-like identifier, unique across the CMDB.
	// Immutable after creation.
	Name string `json:"name"`

	// Provider Underlying Kubernetes distribution or hosting provider.
	// Open-ended; common values: gke, eks, aks, openshift, rke, kubeadm, onprem, other.
	Provider *string `json:"provider,omitempty"`
	Region   *string `json:"region,omitempty"`
}

// ClusterList Paged list of clusters.
type ClusterList struct {
	Items []Cluster `json:"items"`

	// NextCursor Opaque cursor to pass as `?cursor=` to fetch the next page.
	// Absent or null when no more pages remain.
	NextCursor *string `json:"next_cursor,omitempty"`
}

// ClusterMutable Fields on a Cluster that clients may set and later update.
type ClusterMutable struct {
	// ApiEndpoint Kubernetes API server URL (informational).
	ApiEndpoint *string `json:"api_endpoint,omitempty"`

	// DisplayName Human-friendly label, free-form.
	DisplayName *string `json:"display_name,omitempty"`

	// Environment Free-form environment tag (e.g., dev, staging, prod).
	Environment *string `json:"environment,omitempty"`

	// KubernetesVersion Cluster API server version reported by Kubernetes (e.g. "1.29.5").
	KubernetesVersion *string `json:"kubernetes_version,omitempty"`

	// Labels Arbitrary user-supplied string key/value labels.
	Labels *map[string]string `json:"labels,omitempty"`

	// Provider Underlying Kubernetes distribution or hosting provider.
	// Open-ended; common values: gke, eks, aks, openshift, rke, kubeadm, onprem, other.
	Provider *string `json:"provider,omitempty"`
	Region   *string `json:"region,omitempty"`
}

// ClusterUpdate Fields on a Cluster that clients may set and later update.
type ClusterUpdate = ClusterMutable

// Health defines model for Health.
type Health struct {
	Status HealthStatus `json:"status"`

	// Version Build version of the running argosd.
	Version *string `json:"version,omitempty"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// Namespace defines model for Namespace.
type Namespace struct {
	ClusterId openapi_types.UUID `json:"cluster_id"`
	CreatedAt *time.Time         `json:"created_at,omitempty"`

	// DisplayName Human-friendly label, free-form.
	DisplayName *string             `json:"display_name,omitempty"`
	Id          *openapi_types.UUID `json:"id,omitempty"`

	// Labels Arbitrary user-supplied string key/value labels.
	Labels *map[string]string `json:"labels,omitempty"`
	Name   string             `json:"name"`

	// Phase Kubernetes namespace phase as last observed (e.g. "Active", "Terminating").
	// Open-ended to accommodate any additional phases Kubernetes introduces.
	Phase     *string    `json:"phase,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// NamespaceCreate defines model for NamespaceCreate.
type NamespaceCreate struct {
	// ClusterId Parent cluster id. Immutable after creation; the cluster must
	// already exist or the create returns 404.
	ClusterId openapi_types.UUID `json:"cluster_id"`

	// DisplayName Human-friendly label, free-form.
	DisplayName *string `json:"display_name,omitempty"`

	// Labels Arbitrary user-supplied string key/value labels.
	Labels *map[string]string `json:"labels,omitempty"`

	// Name Kubernetes namespace name (DNS-label style). Unique per cluster.
	// Immutable after creation.
	Name string `json:"name"`

	// Phase Kubernetes namespace phase as last observed (e.g. "Active", "Terminating").
	// Open-ended to accommodate any additional phases Kubernetes introduces.
	Phase *string `json:"phase,omitempty"`
}

// NamespaceList Paged list of namespaces.
type NamespaceList struct {
	Items []Namespace `json:"items"`

	// NextCursor Opaque cursor to pass as `?cursor=` to fetch the next page.
	// Absent or null when no more pages remain.
	NextCursor *string `json:"next_cursor,omitempty"`
}

// NamespaceMutable Fields on a Namespace that clients may set and later update.
type NamespaceMutable struct {
	// DisplayName Human-friendly label, free-form.
	DisplayName *string `json:"display_name,omitempty"`

	// Labels Arbitrary user-supplied string key/value labels.
	Labels *map[string]string `json:"labels,omitempty"`

	// Phase Kubernetes namespace phase as last observed (e.g. "Active", "Terminating").
	// Open-ended to accommodate any additional phases Kubernetes introduces.
	Phase *string `json:"phase,omitempty"`
}

// NamespaceUpdate Fields on a Namespace that clients may set and later update.
type NamespaceUpdate = NamespaceMutable

// Node defines model for Node.
type Node struct {
	// Architecture CPU architecture. Open-ended; common values: amd64, arm64, ppc64le, s390x.
	Architecture *string            `json:"architecture,omitempty"`
	ClusterId    openapi_types.UUID `json:"cluster_id"`
	CreatedAt    *time.Time         `json:"created_at,omitempty"`

	// DisplayName Human-friendly label, free-form.
	DisplayName *string             `json:"display_name,omitempty"`
	Id          *openapi_types.UUID `json:"id,omitempty"`

	// KubeletVersion Kubelet git version as reported by Kubernetes (e.g. "v1.29.5").
	KubeletVersion *string `json:"kubelet_version,omitempty"`

	// Labels Arbitrary user-supplied string key/value labels.
	Labels *map[string]string `json:"labels,omitempty"`
	Name   string             `json:"name"`

	// OsImage Node OS image string (e.g. "Ubuntu 22.04.3 LTS").
	OsImage   *string    `json:"os_image,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// NodeCreate defines model for NodeCreate.
type NodeCreate struct {
	// Architecture CPU architecture. Open-ended; common values: amd64, arm64, ppc64le, s390x.
	Architecture *string `json:"architecture,omitempty"`

	// ClusterId Parent cluster id. Immutable after creation; the cluster must
	// already exist or the create returns 404.
	ClusterId openapi_types.UUID `json:"cluster_id"`

	// DisplayName Human-friendly label, free-form.
	DisplayName *string `json:"display_name,omitempty"`

	// KubeletVersion Kubelet git version as reported by Kubernetes (e.g. "v1.29.5").
	KubeletVersion *string `json:"kubelet_version,omitempty"`

	// Labels Arbitrary user-supplied string key/value labels.
	Labels *map[string]string `json:"labels,omitempty"`

	// Name Kubernetes node name (DNS-subdomain style). Unique per cluster.
	// Immutable after creation.
	Name string `json:"name"`

	// OsImage Node OS image string (e.g. "Ubuntu 22.04.3 LTS").
	OsImage *string `json:"os_image,omitempty"`
}

// NodeList Paged list of nodes.
type NodeList struct {
	Items []Node `json:"items"`

	// NextCursor Opaque cursor to pass as `?cursor=` to fetch the next page.
	// Absent or null when no more pages remain.
	NextCursor *string `json:"next_cursor,omitempty"`
}

// NodeMutable Fields on a Node that clients may set and later update.
type NodeMutable struct {
	// Architecture CPU architecture. Open-ended; common values: amd64, arm64, ppc64le, s390x.
	Architecture *string `json:"architecture,omitempty"`

	// DisplayName Human-friendly label, free-form.
	DisplayName *string `json:"display_name,omitempty"`

	// KubeletVersion Kubelet git version as reported by Kubernetes (e.g. "v1.29.5").
	KubeletVersion *string `json:"kubelet_version,omitempty"`

	// Labels Arbitrary user-supplied string key/value labels.
	Labels *map[string]string `json:"labels,omitempty"`

	// OsImage Node OS image string (e.g. "Ubuntu 22.04.3 LTS").
	OsImage *string `json:"os_image,omitempty"`
}

// NodeUpdate Fields on a Node that clients may set and later update.
type NodeUpdate = NodeMutable

// Problem RFC 7807 problem details.
type Problem struct {
	Detail *string `json:"detail,omitempty"`

	// Errors Field-level validation errors, when applicable.
	Errors *[]struct {
		Field   string `json:"field"`
		Message string `json:"message"`
	} `json:"errors,omitempty"`
	Instance *string `json:"instance,omitempty"`
	Status   int     `json:"status"`
	Title    string  `json:"title"`
	Type     string  `json:"type"`
}

// ClusterId defines model for ClusterId.
type ClusterId = openapi_types.UUID

// Cursor defines model for Cursor.
type Cursor = string

// Limit defines model for Limit.
type Limit = int

// NamespaceClusterIdFilter defines model for NamespaceClusterIdFilter.
type NamespaceClusterIdFilter = openapi_types.UUID

// NamespaceId defines model for NamespaceId.
type NamespaceId = openapi_types.UUID

// NodeClusterIdFilter defines model for NodeClusterIdFilter.
type NodeClusterIdFilter = openapi_types.UUID

// NodeId defines model for NodeId.
type NodeId = openapi_types.UUID

// BadRequest RFC 7807 problem details.
type BadRequest = Problem

// Conflict RFC 7807 problem details.
type Conflict = Problem

// Forbidden RFC 7807 problem details.
type Forbidden = Problem

// NotFound RFC 7807 problem details.
type NotFound = Problem

// Unauthorized RFC 7807 problem details.
type Unauthorized = Problem

// ListClustersParams defines parameters for ListClusters.
type ListClustersParams struct {
	// Limit Maximum number of items to return. Server clamps to [1, 200].
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque cursor returned from a previous list response.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// ListNamespacesParams defines parameters for ListNamespaces.
type ListNamespacesParams struct {
	// Limit Maximum number of items to return. Server clamps to [1, 200].
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque cursor returned from a previous list response.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`

	// ClusterId Return only namespaces belonging to this cluster.
	ClusterId *NamespaceClusterIdFilter `form:"cluster_id,omitempty" json:"cluster_id,omitempty"`
}

// ListNodesParams defines parameters for ListNodes.
type ListNodesParams struct {
	// Limit Maximum number of items to return. Server clamps to [1, 200].
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque cursor returned from a previous list response.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`

	// ClusterId Return only nodes belonging to this cluster.
	ClusterId *NodeClusterIdFilter `form:"cluster_id,omitempty" json:"cluster_id,omitempty"`
}

// CreateClusterJSONRequestBody defines body for CreateCluster for application/json ContentType.
type CreateClusterJSONRequestBody = ClusterCreate

// UpdateClusterApplicationMergePatchPlusJSONRequestBody defines body for UpdateCluster for application/merge-patch+json ContentType.
type UpdateClusterApplicationMergePatchPlusJSONRequestBody = ClusterUpdate

// CreateNamespaceJSONRequestBody defines body for CreateNamespace for application/json ContentType.
type CreateNamespaceJSONRequestBody = NamespaceCreate

// UpdateNamespaceApplicationMergePatchPlusJSONRequestBody defines body for UpdateNamespace for application/merge-patch+json ContentType.
type UpdateNamespaceApplicationMergePatchPlusJSONRequestBody = NamespaceUpdate

// CreateNodeJSONRequestBody defines body for CreateNode for application/json ContentType.
type CreateNodeJSONRequestBody = NodeCreate

// UpdateNodeApplicationMergePatchPlusJSONRequestBody defines body for UpdateNode for application/merge-patch+json ContentType.
type UpdateNodeApplicationMergePatchPlusJSONRequestBody = NodeUpdate

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Liveness probe
	// (GET /healthz)
	GetHealthz(w http.ResponseWriter, r *http.Request)
	// Readiness probe
	// (GET /readyz)
	GetReadyz(w http.ResponseWriter, r *http.Request)
	// List clusters
	// (GET /v1/clusters)
	ListClusters(w http.ResponseWriter, r *http.Request, params ListClustersParams)
	// Register a cluster
	// (POST /v1/clusters)
	CreateCluster(w http.ResponseWriter, r *http.Request)
	// Delete a cluster
	// (DELETE /v1/clusters/{id})
	DeleteCluster(w http.ResponseWriter, r *http.Request, id ClusterId)
	// Get a cluster
	// (GET /v1/clusters/{id})
	GetCluster(w http.ResponseWriter, r *http.Request, id ClusterId)
	// Update mutable fields of a cluster
	// (PATCH /v1/clusters/{id})
	UpdateCluster(w http.ResponseWriter, r *http.Request, id ClusterId)
	// List namespaces
	// (GET /v1/namespaces)
	ListNamespaces(w http.ResponseWriter, r *http.Request, params ListNamespacesParams)
	// Register a namespace
	// (POST /v1/namespaces)
	CreateNamespace(w http.ResponseWriter, r *http.Request)
	// Delete a namespace
	// (DELETE /v1/namespaces/{id})
	DeleteNamespace(w http.ResponseWriter, r *http.Request, id NamespaceId)
	// Get a namespace
	// (GET /v1/namespaces/{id})
	GetNamespace(w http.ResponseWriter, r *http.Request, id NamespaceId)
	// Update mutable fields of a namespace
	// (PATCH /v1/namespaces/{id})
	UpdateNamespace(w http.ResponseWriter, r *http.Request, id NamespaceId)
	// List nodes
	// (GET /v1/nodes)
	ListNodes(w http.ResponseWriter, r *http.Request, params ListNodesParams)
	// Register a node
	// (POST /v1/nodes)
	CreateNode(w http.ResponseWriter, r *http.Request)
	// Delete a node
	// (DELETE /v1/nodes/{id})
	DeleteNode(w http.ResponseWriter, r *http.Request, id NodeId)
	// Get a node
	// (GET /v1/nodes/{id})
	GetNode(w http.ResponseWriter, r *http.Request, id NodeId)
	// Update mutable fields of a node
	// (PATCH /v1/nodes/{id})
	UpdateNode(w http.ResponseWriter, r *http.Request, id NodeId)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHealthz operation middleware
func (siw *ServerInterfaceWrapper) GetHealthz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealthz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetReadyz operation middleware
func (siw *ServerInterfaceWrapper) GetReadyz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetReadyz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListClusters operation middleware
func (siw *ServerInterfaceWrapper) ListClusters(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"read"})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListClustersParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListClusters(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateCluster operation middleware
func (siw *ServerInterfaceWrapper) CreateCluster(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"write"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateCluster(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteCluster operation middleware
func (siw *ServerInterfaceWrapper) DeleteCluster(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ClusterId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"delete"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteCluster(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCluster operation middleware
func (siw *ServerInterfaceWrapper) GetCluster(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ClusterId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"read"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCluster(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateCluster operation middleware
func (siw *ServerInterfaceWrapper) UpdateCluster(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ClusterId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"write"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateCluster(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListNamespaces operation middleware
func (siw *ServerInterfaceWrapper) ListNamespaces(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"read"})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListNamespacesParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		return
	}

	// ------------- Optional query parameter "cluster_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cluster_id", r.URL.Query(), &params.ClusterId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cluster_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListNamespaces(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateNamespace operation middleware
func (siw *ServerInterfaceWrapper) CreateNamespace(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"write"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateNamespace(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteNamespace operation middleware
func (siw *ServerInterfaceWrapper) DeleteNamespace(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id NamespaceId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"delete"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteNamespace(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetNamespace operation middleware
func (siw *ServerInterfaceWrapper) GetNamespace(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id NamespaceId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"read"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetNamespace(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateNamespace operation middleware
func (siw *ServerInterfaceWrapper) UpdateNamespace(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id NamespaceId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"write"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateNamespace(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListNodes operation middleware
func (siw *ServerInterfaceWrapper) ListNodes(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"read"})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListNodesParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		return
	}

	// ------------- Optional query parameter "cluster_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cluster_id", r.URL.Query(), &params.ClusterId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cluster_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListNodes(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateNode operation middleware
func (siw *ServerInterfaceWrapper) CreateNode(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"write"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateNode(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteNode operation middleware
func (siw *ServerInterfaceWrapper) DeleteNode(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id NodeId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"delete"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteNode(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetNode operation middleware
func (siw *ServerInterfaceWrapper) GetNode(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id NodeId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"read"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetNode(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateNode operation middleware
func (siw *ServerInterfaceWrapper) UpdateNode(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id NodeId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"write"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateNode(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/healthz", wrapper.GetHealthz)
	m.HandleFunc("GET "+options.BaseURL+"/readyz", wrapper.GetReadyz)
	m.HandleFunc("GET "+options.BaseURL+"/v1/clusters", wrapper.ListClusters)
	m.HandleFunc("POST "+options.BaseURL+"/v1/clusters", wrapper.CreateCluster)
	m.HandleFunc("DELETE "+options.BaseURL+"/v1/clusters/{id}", wrapper.DeleteCluster)
	m.HandleFunc("GET "+options.BaseURL+"/v1/clusters/{id}", wrapper.GetCluster)
	m.HandleFunc("PATCH "+options.BaseURL+"/v1/clusters/{id}", wrapper.UpdateCluster)
	m.HandleFunc("GET "+options.BaseURL+"/v1/namespaces", wrapper.ListNamespaces)
	m.HandleFunc("POST "+options.BaseURL+"/v1/namespaces", wrapper.CreateNamespace)
	m.HandleFunc("DELETE "+options.BaseURL+"/v1/namespaces/{id}", wrapper.DeleteNamespace)
	m.HandleFunc("GET "+options.BaseURL+"/v1/namespaces/{id}", wrapper.GetNamespace)
	m.HandleFunc("PATCH "+options.BaseURL+"/v1/namespaces/{id}", wrapper.UpdateNamespace)
	m.HandleFunc("GET "+options.BaseURL+"/v1/nodes", wrapper.ListNodes)
	m.HandleFunc("POST "+options.BaseURL+"/v1/nodes", wrapper.CreateNode)
	m.HandleFunc("DELETE "+options.BaseURL+"/v1/nodes/{id}", wrapper.DeleteNode)
	m.HandleFunc("GET "+options.BaseURL+"/v1/nodes/{id}", wrapper.GetNode)
	m.HandleFunc("PATCH "+options.BaseURL+"/v1/nodes/{id}", wrapper.UpdateNode)

	return m
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xc63Lbtpd/lTPczqydUrJ8Sdoos9NxnKb1NHE8drz7wfLGEHEkoQIBBgDlqBnN7EPs",
	"E+6T7ADgTRJ1S2z9E7dfbIoEcA7O9ceDI30OIhknUqAwOmh/DhKiSIwGlft0wlNtUJ1S+4GijhRLDJMi",
	"aAeXqEaoGkRr1hdIIfJDgVEUhvUYqmYQBswOTYgZBGEgSIxBO2A0CAOFH1OmkAZto1IMAx0NMCaWSk+q",
	"mJigHaSpG2nGiZ2ljWKiH0wmYXCSKi3VPEfvEvIxRYjcY1BoUmUZ6ykZA4FE4YjJVANn2oBCnUihseDx",
	"Y4pqXDLpFwmqjMXk0xsUfTMI2k/3D+oYe8NiZub5eks+sTiNQaRxFxXIHjCDsQYjMyab4IUJESdx4h5c",
	"74dw0GrdLOKPO1JV9ij2SMpN0H7aCi2vlmTQPmjZT0z4T/sF10wY7KNybJ+RGHVCIiy0/ZpxgzUSvnDs",
	"ghR8DCKfpaGLXIo+E33LuRkwnRvDQun6xx+cgjdRfcHqOhZZcLgFmzyTdEPxSbpdyUm6ntAkfXh5Texk",
	"74AuzLwk9AI/pqid90RSGBTukiQJZxGxvO4lSnY5xj/+qS3jnyvkflDYC9rBv+2VoWzPP9V7536WJzrr",
	"l9wyihSUJ94MbHSRosdZtFVOcppwx8zABjCFwoA2xCDsYLPfDIGmnj46s951rL6WqssoRbFNXt/LIQpg",
	"GkaEMwrd1AAn0VCDGSDoSCYIuWFAd+zuygSV48ZxfSbNa5kKuk2mL1DLVEUIQhroWeqOlStBUjOQiv2F",
	"W2XnLdPaOr1UwEQmRyQKFRgr3abz2GydShp2fHH+rhe0r5fTzia8TQ3pcgwm4ecgUVYNhnmPixQSg/QD",
	"MVP+SonBhmExOvcm9J3g49y9Z5w4tEGgxtdXTvMhZCqfPjtySSr/eBDacGNQWVn99zVp/NVqPL/J/jdu",
	"PrfCZweT/PYPQQ2NNKFfub1JNb5d+4DnOA+rspuidFMsIrt/YmSCyc2s4o/hj7SLSqDBItSDwj6zF0iB",
	"CecwJ29fvfTByA85cRTvUf25DmZygRsOmqf9BmfDah4IIRXMoisSKal1yWVHnMaxpwOkZ7fjxGOdvSOC",
	"8AG1PKMht6U1VHBOxlwS6tGXFzwQEHhXpt5S8G+YrgF056SP1ONI2cunaZsqp6XsYN7UxRpKs9SzPRCl",
	"yNi5DH4yH6K1YK+RkBCtgWi4/cXf+49be7eHJho4vdnVICF9bHbEcVfbVCMViJRzuBugACEhlgrdEA0K",
	"Y8IyZdoxzqLW8xm363mVFNLN7XNuS68ZcqpBCiCQjQUzIAYizqzMICZj0GiACAqc2MfeD+d1QBL2AQVN",
	"JBM1mqx44/H5KWgPw68u3sAOEz5sMCkI37ULl5FOsbqgQ5lOOBl/qHeu39OYiEZPMRSUj4GTLvIQegqx",
	"YRduTvvKwdNnNRRQjJiSIsa6vbzOl4LKMDCkX0AIHIUWVFi8GUKiJN1tznvoHNFhIaMPI1Sa+Rw4A2Ay",
	"JVWEmI0FhYlUxoOBirgdT9AJ9psHz5tPO8EsK4cHNaw4oXm1Usq8as6n1L1ShDPxWHWZUUSNIdWoGjq1",
	"WR8p+PEwxPHeiPAUvbp0xmOVZEVkpX0nSo4YrXsFuBIUFR/bxSvCoMwS7KZ2kPXFgdTGDsnXaXbEuwRF",
	"AwVF+gIiGcdSgONMt6E/xBBwqEMg9o9MUOgB65kQlH1i9UdoHIIUiUL73wzckmvo3kZIr+/lIyeLnfzK",
	"OeaX5665AP4WVR8bCbHhrCvpuAk2jUOehHoudryAW+uGtxaosjxBWTHGzFhj9KOAKASOPQOpiAZE9JFa",
	"uUzC4Hck3O51NnFaTJ66KxT2jfo6kMNKiCslt9BVXqaM08I7ZM+FZJUKYRVOVF9q2lyZ7DI26mJr8Yq8",
	"vsiLKUvwYvneufr9LvzW4OXhFPDYrwUeO9eN7OpJfmv3ly2Cy6k3+3tGmmUlZAnWLMtAG6LNjc1nFk25",
	"t92yftiERZDyheM4Hxmn2nQE4VbYY8BPDo8pP8RtISuvaThqHfl4t9Jw63N3rSjtFey8OrtsuOQA2ow5",
	"7jbhygPlxNXzPKLcBCTfp63O2Nm8iX0VXi5FkdqsBmQKQRdWsQ6GLouJX4uiy/D3N8DRc563FEkXo78U",
	"Sz88wP1uAN6A6HXjhBtr7YgTa+xdh49pAYCPI8NG2AlC6ATvUcVMEIv9LCKuoj5reiRyyM8qB4gYQykj",
	"T0RXYz4TRkmaWpeajTGHB2sBuMJeNoVw8wnhi0FcGbJunYFmqI4o7IgS18G6sO5M0k32IeljhUQHTw/X",
	"KMYUeab5GEGRpMvxkKSbQ6ENLOa7RkFWdiUA0mmXSpve7gkE3bN1PjAMsrKoRUCSrgd+JL0H3GMj298B",
	"8lQ8bDnasWr50qKhigbMYGRSVUPl5PwKqiOasKQ4Q2L67CgEomL7L0miZ0ccQ9CHz1uf1knM2ygrDtMu",
	"cjSLy3t/+AHQZ6aoXBC9qrQ3epS1Pak/sJj0a1ThLO7dJbjHOZlcGFfdVJgUDg6araPmIbx5fzkvl7pd",
	"TRb4wMaYrJqZvhU4lh+RzndKvD6Bn35u/QTZ0StQNITxmijpH9ir+Wq5UlLpBVGiwXGE3B9iuyQEfnjo",
	"A1l2/Gt3E4RlBJ6m7bZXSzpGrTMbWR7o/BLlhLqQNxvSmdCGCF/gW3UmUdYri5agp8+fV1uCWq35pqAw",
	"MMxwrN2av1HpNwpIV6am3eVEDFeeksxs3z3NqYWLy5p2JxilipnxpTXorG3EnZkfp75Q60/QX+fk3Ul6",
	"MBcUzk/9GTswrVOkIFPTkL1GlwjahEsU1KW/46wtwFlGGzwh6KSt1mHkprtLvG12REdcRjJBDX1FhMle",
	"1DyNdkcANODWQrNbAPi///lfn/St6/TRlI0ROht5p5jBWz8yQ292rM9TsMNiG8J0viIxHuYRzlH9uztG",
	"iBTa9Xaz9agN23jr1lMYy5FFg74VIidJaMxERpJwnlekSVeO8IUd7V9Xe1JBL7XpDtyMhutiyk/WtJWD",
	"6wzREBGl3AGHXSZf3jeGOP4jZvgYNDFM98buPXa6a6QjuvZ2pWvEpUkXyKxNeD2XpjUwJvFNFkz0ZE0s",
	"+fXyvTuYslt48uRY9aV+8iQE4qC+u1tJXpWzMw2E+6Yo15ZjBtgRx2eXl6dwidFZGp9wmVLYuTw72YWP",
	"KeGslzWMQE+RGO+kGjr7eD9gukibO63mfrO1C0wDgTvCh1ZSemj1JAVEcoTWUTLLecNGKNBCMkHB6py5",
	"TzYoFvrLzktuC8XCycXVK2eXaVfjx9SCtIy6hjvGORBKHTwKy5JQCP8l1dAi3BDOJQ0dRXdQ1BFT0jHM",
	"jGHIBLV4KkmsBwnXu4bgZRMRZWRfkWRg0cgYlXZC+NVFV+hJzuUdFPF953ZRo83tbqb3NI6JGk+9fzQi",
	"FEaxyGtwVkswr6RSIUW0sQChL7Vf4vj8NKic2QROSS7bJyhIwoJ2cOhuuReRgYs+ewN3RvSXve6jQ/mF",
	"yZ7SoB38hub3bMhMv9tBq7Wk3WizNqPspKqmy+gS1YhF6EyNsxE2p+Jo0L6+qUq3sDVnXVZMpK9tjPbb",
	"DG7s5D33llnd8jTJ/0TFejZCUXkntFFIbOpOLDQWkb2/Q4khXaJx16EChSQa5Fl2TnoXnti/Wnj+zdpI",
	"f7INRpFej0XuFe9p63CbfWMVpoQ0nrHlWr2YDhqL1Dra38vbWBaas32VPckHhVON4guwZzlkz7dGT8KV",
	"A7PmbgtRH0zr1eaeGikvau+ZhMGR56Ju8YLbvUo3q5uyv3rKVCOim3S4elLZ/jljAdPI6NoV3oKbyYy7",
	"66LapCtmUdy6mYRBInWNIfiiWN6u5AEdavNS0vF9qyirv02mcaNRKU7m7GP/vonXdupmVbesCGnD1gAJ",
	"zfzmjfT0avo+Lk5zZCXwjo/zBar93nX907UYevINW6Kd8Xz1jKLLeoXpOkA8a7sXZQEuKqywxoBnItve",
	"Z0YnXjUWFc8b9it3v2rYUwZ2tLjvya9Im1sV89HqGUWv9QoxZxKZkbOXxyophwvRz0JJtrbpqkXp4DvV",
	"TV30/g3NarVslqHLr3pZUq4UVPNVpkqdSGNMhGGRbud1HpmXfZSMXajrSjp2OK9a+KlpzKo9D5g2J1/v",
	"2jTpxCW/P36RYWVltrUS0Fas2jNEpw4avuVccI+OUJsLvDxmKpU21a6XG8rGk6W496wc9uDId/XIhV/Y",
	"e1DUPN3QsxI3V1t6Hh9yFlWDyM2rcnMVei7blB4GP882820ZQVe6sObtpOxDujcUXUj+UeHojWLnloG3",
	"qBhwrf3PBdg14fe0Z6wC4KUtPXIIvlLei2H4Eom2tu3xjxeMr6GgzYBD9bvuDw3JF5/rfgFI3zy3fTlM",
	"n+1R3DJQX2r1OVSvJKd/wPoisL52PpF0FVZ3I74FmF7zmxAPi9DzhrPV4Ny3nD1CXJ4pvzAh93klGpf0",
	"wYB42UW6bQzuOgJrkrGk94m8Jf0HdG8NdHs7nTXuamhcF2XnFr8SYFtreezYul6sSxB1rfRa23HdRwyh",
	"F+lhQ+Dsf+ro+8LMm2Sgr4DLZefotpHyApMuQLLLI//g44X4eEHoX0rFL+9+j8F7zrTsbbrnQHGEXCbu",
	"RyXCIFU866lr7+1xO2AgtWn/3Pq55TwqY2BuqWWdarCTOuGj9TOrbdf4nP2UWNaHYvH0wq+b5HX7hV/X",
	"mf19NL18Pf/jazt3Ug1RwR5YC1eSNxJOBEJMooFlf9d1lDFR/VpHQcgrYDmV8hfyli1UvuRMbib/HwAA",
	"//8ULbQij1EAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
