//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for HealthStatus.
const (
	Ok HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Cluster defines model for Cluster.
type Cluster struct {
	// ApiEndpoint Kubernetes API server URL (informational).
	ApiEndpoint *string    `json:"api_endpoint,omitempty"`
	CreatedAt   *time.Time `json:"created_at,omitempty"`

	// DisplayName Human-friendly label, free-form.
	DisplayName *string `json:"display_name,omitempty"`

	// Environment Free-form environment tag (e.g., dev, staging, prod).
	Environment *string             `json:"environment,omitempty"`
	Id          *openapi_types.UUID `json:"id,omitempty"`

	// KubernetesVersion Cluster API server version reported by Kubernetes (e.g. "1.29.5").
	KubernetesVersion *string `json:"kubernetes_version,omitempty"`

	// Labels Arbitrary user-supplied string key/value labels.
	Labels *map[string]string `json:"labels,omitempty"`
	Name   string             `json:"name"`

	// Provider Underlying Kubernetes distribution or hosting provider.
	// Open-ended; common values: gke, eks, aks, openshift, rke, kubeadm, onprem, other.
	Provider  *string    `json:"provider,omitempty"`
	Region    *string    `json:"region,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// ClusterCreate defines model for ClusterCreate.
type ClusterCreate struct {
	// ApiEndpoint Kubernetes API server URL (informational).
	ApiEndpoint *string `json:"api_endpoint,omitempty"`

	// DisplayName Human-friendly label, free-form.
	DisplayName *string `json:"display_name,omitempty"`

	// Environment Free-form environment tag (e.g., dev, staging, prod).
	Environment *string `json:"environment,omitempty"`

	// KubernetesVersion Cluster API server version reported by Kubernetes (e.g. "1.29.5").
	KubernetesVersion *string `json:"kubernetes_version,omitempty"`

	// Labels Arbitrary user-supplied string key/value labels.
	Labels *map[string]string `json:"labels,omitempty"`

	// Name Stable slug-like identifier, unique across the CMDB.
	// Immutable after creation.
	Name string `json:"name"`

	// Provider Underlying Kubernetes distribution or hosting provider.
	// Open-ended; common values: gke, eks, aks, openshift, rke, kubeadm, onprem, other.
	Provider *string `json:"provider,omitempty"`
	Region   *string `json:"region,omitempty"`
}

// ClusterList Paged list of clusters.
type ClusterList struct {
	Items []Cluster `json:"items"`

	// NextCursor Opaque cursor to pass as `?cursor=` to fetch the next page.
	// Absent or null when no more pages remain.
	NextCursor *string `json:"next_cursor,omitempty"`
}

// ClusterMutable Fields on a Cluster that clients may set and later update.
type ClusterMutable struct {
	// ApiEndpoint Kubernetes API server URL (informational).
	ApiEndpoint *string `json:"api_endpoint,omitempty"`

	// DisplayName Human-friendly label, free-form.
	DisplayName *string `json:"display_name,omitempty"`

	// Environment Free-form environment tag (e.g., dev, staging, prod).
	Environment *string `json:"environment,omitempty"`

	// KubernetesVersion Cluster API server version reported by Kubernetes (e.g. "1.29.5").
	KubernetesVersion *string `json:"kubernetes_version,omitempty"`

	// Labels Arbitrary user-supplied string key/value labels.
	Labels *map[string]string `json:"labels,omitempty"`

	// Provider Underlying Kubernetes distribution or hosting provider.
	// Open-ended; common values: gke, eks, aks, openshift, rke, kubeadm, onprem, other.
	Provider *string `json:"provider,omitempty"`
	Region   *string `json:"region,omitempty"`
}

// ClusterUpdate Fields on a Cluster that clients may set and later update.
type ClusterUpdate = ClusterMutable

// Health defines model for Health.
type Health struct {
	Status HealthStatus `json:"status"`

	// Version Build version of the running argosd.
	Version *string `json:"version,omitempty"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// Node defines model for Node.
type Node struct {
	// Architecture CPU architecture. Open-ended; common values: amd64, arm64, ppc64le, s390x.
	Architecture *string            `json:"architecture,omitempty"`
	ClusterId    openapi_types.UUID `json:"cluster_id"`
	CreatedAt    *time.Time         `json:"created_at,omitempty"`

	// DisplayName Human-friendly label, free-form.
	DisplayName *string             `json:"display_name,omitempty"`
	Id          *openapi_types.UUID `json:"id,omitempty"`

	// KubeletVersion Kubelet git version as reported by Kubernetes (e.g. "v1.29.5").
	KubeletVersion *string `json:"kubelet_version,omitempty"`

	// Labels Arbitrary user-supplied string key/value labels.
	Labels *map[string]string `json:"labels,omitempty"`
	Name   string             `json:"name"`

	// OsImage Node OS image string (e.g. "Ubuntu 22.04.3 LTS").
	OsImage   *string    `json:"os_image,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// NodeCreate defines model for NodeCreate.
type NodeCreate struct {
	// Architecture CPU architecture. Open-ended; common values: amd64, arm64, ppc64le, s390x.
	Architecture *string `json:"architecture,omitempty"`

	// ClusterId Parent cluster id. Immutable after creation; the cluster must
	// already exist or the create returns 404.
	ClusterId openapi_types.UUID `json:"cluster_id"`

	// DisplayName Human-friendly label, free-form.
	DisplayName *string `json:"display_name,omitempty"`

	// KubeletVersion Kubelet git version as reported by Kubernetes (e.g. "v1.29.5").
	KubeletVersion *string `json:"kubelet_version,omitempty"`

	// Labels Arbitrary user-supplied string key/value labels.
	Labels *map[string]string `json:"labels,omitempty"`

	// Name Kubernetes node name (DNS-subdomain style). Unique per cluster.
	// Immutable after creation.
	Name string `json:"name"`

	// OsImage Node OS image string (e.g. "Ubuntu 22.04.3 LTS").
	OsImage *string `json:"os_image,omitempty"`
}

// NodeList Paged list of nodes.
type NodeList struct {
	Items []Node `json:"items"`

	// NextCursor Opaque cursor to pass as `?cursor=` to fetch the next page.
	// Absent or null when no more pages remain.
	NextCursor *string `json:"next_cursor,omitempty"`
}

// NodeMutable Fields on a Node that clients may set and later update.
type NodeMutable struct {
	// Architecture CPU architecture. Open-ended; common values: amd64, arm64, ppc64le, s390x.
	Architecture *string `json:"architecture,omitempty"`

	// DisplayName Human-friendly label, free-form.
	DisplayName *string `json:"display_name,omitempty"`

	// KubeletVersion Kubelet git version as reported by Kubernetes (e.g. "v1.29.5").
	KubeletVersion *string `json:"kubelet_version,omitempty"`

	// Labels Arbitrary user-supplied string key/value labels.
	Labels *map[string]string `json:"labels,omitempty"`

	// OsImage Node OS image string (e.g. "Ubuntu 22.04.3 LTS").
	OsImage *string `json:"os_image,omitempty"`
}

// NodeUpdate Fields on a Node that clients may set and later update.
type NodeUpdate = NodeMutable

// Problem RFC 7807 problem details.
type Problem struct {
	Detail *string `json:"detail,omitempty"`

	// Errors Field-level validation errors, when applicable.
	Errors *[]struct {
		Field   string `json:"field"`
		Message string `json:"message"`
	} `json:"errors,omitempty"`
	Instance *string `json:"instance,omitempty"`
	Status   int     `json:"status"`
	Title    string  `json:"title"`
	Type     string  `json:"type"`
}

// ClusterId defines model for ClusterId.
type ClusterId = openapi_types.UUID

// Cursor defines model for Cursor.
type Cursor = string

// Limit defines model for Limit.
type Limit = int

// NodeClusterIdFilter defines model for NodeClusterIdFilter.
type NodeClusterIdFilter = openapi_types.UUID

// NodeId defines model for NodeId.
type NodeId = openapi_types.UUID

// BadRequest RFC 7807 problem details.
type BadRequest = Problem

// Conflict RFC 7807 problem details.
type Conflict = Problem

// Forbidden RFC 7807 problem details.
type Forbidden = Problem

// NotFound RFC 7807 problem details.
type NotFound = Problem

// Unauthorized RFC 7807 problem details.
type Unauthorized = Problem

// ListClustersParams defines parameters for ListClusters.
type ListClustersParams struct {
	// Limit Maximum number of items to return. Server clamps to [1, 200].
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque cursor returned from a previous list response.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// ListNodesParams defines parameters for ListNodes.
type ListNodesParams struct {
	// Limit Maximum number of items to return. Server clamps to [1, 200].
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque cursor returned from a previous list response.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`

	// ClusterId Return only nodes belonging to this cluster.
	ClusterId *NodeClusterIdFilter `form:"cluster_id,omitempty" json:"cluster_id,omitempty"`
}

// CreateClusterJSONRequestBody defines body for CreateCluster for application/json ContentType.
type CreateClusterJSONRequestBody = ClusterCreate

// UpdateClusterApplicationMergePatchPlusJSONRequestBody defines body for UpdateCluster for application/merge-patch+json ContentType.
type UpdateClusterApplicationMergePatchPlusJSONRequestBody = ClusterUpdate

// CreateNodeJSONRequestBody defines body for CreateNode for application/json ContentType.
type CreateNodeJSONRequestBody = NodeCreate

// UpdateNodeApplicationMergePatchPlusJSONRequestBody defines body for UpdateNode for application/merge-patch+json ContentType.
type UpdateNodeApplicationMergePatchPlusJSONRequestBody = NodeUpdate

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Liveness probe
	// (GET /healthz)
	GetHealthz(w http.ResponseWriter, r *http.Request)
	// Readiness probe
	// (GET /readyz)
	GetReadyz(w http.ResponseWriter, r *http.Request)
	// List clusters
	// (GET /v1/clusters)
	ListClusters(w http.ResponseWriter, r *http.Request, params ListClustersParams)
	// Register a cluster
	// (POST /v1/clusters)
	CreateCluster(w http.ResponseWriter, r *http.Request)
	// Delete a cluster
	// (DELETE /v1/clusters/{id})
	DeleteCluster(w http.ResponseWriter, r *http.Request, id ClusterId)
	// Get a cluster
	// (GET /v1/clusters/{id})
	GetCluster(w http.ResponseWriter, r *http.Request, id ClusterId)
	// Update mutable fields of a cluster
	// (PATCH /v1/clusters/{id})
	UpdateCluster(w http.ResponseWriter, r *http.Request, id ClusterId)
	// List nodes
	// (GET /v1/nodes)
	ListNodes(w http.ResponseWriter, r *http.Request, params ListNodesParams)
	// Register a node
	// (POST /v1/nodes)
	CreateNode(w http.ResponseWriter, r *http.Request)
	// Delete a node
	// (DELETE /v1/nodes/{id})
	DeleteNode(w http.ResponseWriter, r *http.Request, id NodeId)
	// Get a node
	// (GET /v1/nodes/{id})
	GetNode(w http.ResponseWriter, r *http.Request, id NodeId)
	// Update mutable fields of a node
	// (PATCH /v1/nodes/{id})
	UpdateNode(w http.ResponseWriter, r *http.Request, id NodeId)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHealthz operation middleware
func (siw *ServerInterfaceWrapper) GetHealthz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealthz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetReadyz operation middleware
func (siw *ServerInterfaceWrapper) GetReadyz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetReadyz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListClusters operation middleware
func (siw *ServerInterfaceWrapper) ListClusters(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"read"})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListClustersParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListClusters(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateCluster operation middleware
func (siw *ServerInterfaceWrapper) CreateCluster(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"write"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateCluster(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteCluster operation middleware
func (siw *ServerInterfaceWrapper) DeleteCluster(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ClusterId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"delete"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteCluster(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCluster operation middleware
func (siw *ServerInterfaceWrapper) GetCluster(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ClusterId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"read"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCluster(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateCluster operation middleware
func (siw *ServerInterfaceWrapper) UpdateCluster(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ClusterId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"write"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateCluster(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListNodes operation middleware
func (siw *ServerInterfaceWrapper) ListNodes(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"read"})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListNodesParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		return
	}

	// ------------- Optional query parameter "cluster_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cluster_id", r.URL.Query(), &params.ClusterId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cluster_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListNodes(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateNode operation middleware
func (siw *ServerInterfaceWrapper) CreateNode(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"write"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateNode(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteNode operation middleware
func (siw *ServerInterfaceWrapper) DeleteNode(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id NodeId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"delete"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteNode(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetNode operation middleware
func (siw *ServerInterfaceWrapper) GetNode(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id NodeId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"read"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetNode(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateNode operation middleware
func (siw *ServerInterfaceWrapper) UpdateNode(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id NodeId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"write"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateNode(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/healthz", wrapper.GetHealthz)
	m.HandleFunc("GET "+options.BaseURL+"/readyz", wrapper.GetReadyz)
	m.HandleFunc("GET "+options.BaseURL+"/v1/clusters", wrapper.ListClusters)
	m.HandleFunc("POST "+options.BaseURL+"/v1/clusters", wrapper.CreateCluster)
	m.HandleFunc("DELETE "+options.BaseURL+"/v1/clusters/{id}", wrapper.DeleteCluster)
	m.HandleFunc("GET "+options.BaseURL+"/v1/clusters/{id}", wrapper.GetCluster)
	m.HandleFunc("PATCH "+options.BaseURL+"/v1/clusters/{id}", wrapper.UpdateCluster)
	m.HandleFunc("GET "+options.BaseURL+"/v1/nodes", wrapper.ListNodes)
	m.HandleFunc("POST "+options.BaseURL+"/v1/nodes", wrapper.CreateNode)
	m.HandleFunc("DELETE "+options.BaseURL+"/v1/nodes/{id}", wrapper.DeleteNode)
	m.HandleFunc("GET "+options.BaseURL+"/v1/nodes/{id}", wrapper.GetNode)
	m.HandleFunc("PATCH "+options.BaseURL+"/v1/nodes/{id}", wrapper.UpdateNode)

	return m
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xb/XIbtxF/lZ1rZio5xw992Inp6WRkOU40sWWNZLV/iKoFHpYkQhxwBnCUGQ9n+hB9",
	"wj5JZ4E78kgeRcmR1NTtPzZ53MMu9vOHXehzlOg00wqVs1Hnc5Qxw1J0aPy3Q5lbh+aI0xeONjEic0Kr",
	"qBOdoRmjaTBrxUAhhySQguConOgLNM0ojgSRZswNozhSLMWoEwkexZHBj7kwyKOOMznGkU2GmDLi0tcm",
	"ZS7qRHnuKd0ko7esM0INouk0jg5zY7VZlehdxj7mCIn/GQy63JBgfaNTYJAZHAudW5DCOjBoM60szmT8",
	"mKOZzIUMi0RVwVL26Q2qgRtGnac7u3WCvRGpcKtyvWWfRJqnoPK0hwZ0H4TD1ILThZBNCMqERLI08z9c",
	"7MSw225frpNPelZV8Tj2WS5d1HnajklWYhl1dtv0TajwbWcmtVAOB2i82Mea48zQr4V0WKPcUy8paCUn",
	"oDRHCz2UWg2EGpC8bihs6QJrdRp+/uDNeheDk4C3cUGS68H9b0ovB+fxIfKS8VP8mKP1lk+0cqj8R5Zl",
	"UiSMZG1lRvckpt/+aknwzxV23xjsR53oT615GLbCr7Z1Et4KTJd9SpKgyMEE5s2IIkOrvhTJo0pS8oRr",
	"4YYUfAaVA+uYQ9jC5qAZA88DfwQywbYX9bU2PcE5qseU9b0eoQJhYcyk4NDLHUiWjCy4IYJNdIZQOgb0",
	"Jv6pztB4abzUx9q91rnijyn0KVqdmwRBaQd94u5FOVcsd0NtxG/4qOK8FdZS0GsDQhV6RGbQgCPtNn3E",
	"FutUSoiXS8p3/ahzcTPv4oW3uWM9idE0/hxlhszgRIi4xCBzyD8wtxCvnDlsOJGiD2/G3yk5KcN7KYhj",
	"SgI1sb7xtZBCFmrBs32fYMuvuzGlG4eGdPX3C9b4rd14fln837j83I6f7U7Lx99ENTzyjP/O7U2r+e0i",
	"JDwveVzV3QKny9kiuvcrJi6aXi4b/gB+yXtoFDqcpXowOBD0ATkI5QPm8O2rlyEZBZJDz/EezV/aYKkW",
	"eHKwMh80pBhV60AMuRKEDFhitLVzKbvqKE0DH2B92o5XDwV7V0XxA1p5yUJ+S7cwwQmbSM14QA5B8cBA",
	"4fW89M4V/0bYGjBywgbIAwbS/fI1S6VyUcseoix8uIXRiHuxB2YMm/iQwU/uQ3IryOY0ZMxaYBaufgjP",
	"/nJFT/vokqG3G60GGRtgs6sOepZKjTagcinheogKlIZUG/QkFgymTBTGJBrvUbeLGb/rVZPMtFv658qW",
	"XguU3IJWwKCgBTdkDhIpSGeQsglYdMAUB8no5xCHqzZgmfiAimdaqBpLVqLx4OQIbICQ56dvYEuokDaE",
	"Vkxu08LzTGdEXdLhwmaSTT7UB9fPecpUo28EKi4nIFkPZQx9g9ighZuLsbL79FkNB1RjYbRKsW4vr8ul",
	"oEIGjg1mEALHMYEKwpsxZEbz7eZqhK4wHc109GGMxopQA5cATGGkihILWjCYaeMCGKio28sE3Winufu8",
	"+bQbLYuyt1sjildaMCvnIpjmZMHcG1W4lI9NTzjDzARyi6Zhc6r6yCHQwwgnrTGTOQZz2ULGKsuKyub+",
	"nRk9FrzuCHCuOBo5ocUryuCCGPZyIqJYHGrriKRcp9lV7zJUDVQc+QtIdJpqBV4y24HBCGPAkY2B0T86",
	"Q2WHou9iMPQL2Y/xNAatMoP0vxv6JW9he8qQwd43U07XB/m5D8wvr10rCfwtmgE2MkbprKf5pAlUxqEs",
	"Qn2fO17AFYXhFQFVURYoUmMqHDljoAJmECT2HeQqGTI1QE56mcbRz8gk7XW5cBImz/0nVHQavIj0qJLi",
	"5ppbGyovcyH5LDp036dkkytFBmdmoC1vbix2hRh1uZUOerfXNlHfgBLnp83Np7r4DwYqd5/u3QJvbF00",
	"wqfm5ZPy2fYPjwgqF07094ww/WH+BnjpuxZ3xJZ38Zhl2OSPtfMmVxPWYccXXs6SMs2t6yomSbsTwE8e",
	"eJlA4qUvekAW9tv7IbFt9NX6Ir2sO6KCrVfHZw2b97gmJATWTSRuN+E8AOLM95wCcrwDGL5n71zyrFWn",
	"+l3I2Osip9IFbAEmkzPcBiP7btfvBcg+s/0PoONqhN0IjYnwi3GxSYbCYeJyU8Pl8OQcqhRNuAF/sJQ/",
	"24+BmZT+y7Lk2b7EGOze8/anFb+vxXUPj5wJBEl06xHsL4EABsLNijOzm9Dr+KuEr9p+ECkb1JjCe9y7",
	"M/A/l2xKZZz3cuVy2N1ttvebe/Dm/dmqXup2NV0TA3dFjguV6Yth4zx1XvkwKnAkM9hVcyQJtwWSZRdw",
	"dRjw+hC++779HRTdReDomJA1WTL8QJ9WD4TGaGPXZImGxDHK0Kf1RQgCeRwSWdHhpN1E8TwDL/L226tl",
	"naK1hY/cnOjCEvMX6lLeckoXyjqmElzEgvXH7jkkn01snj5/Xp3YtNurM5s4csJJrN1aeFAZB0Wsp3PX",
	"6UmmRhsbAUvb97+W3OL1yJ12gkluhJuckUMXkxHfFj7Iw1kkNIlfl+x9szhaSQonR6GNDMLaHDno3DV0",
	"v9FjijfhDBX35e+g6Hx7z+hAYATdvN3eS/zr/iNeNbuqq84SnaGFgWGKnN5pYIFHp6sAGnBF0OwKAP71",
	"j3+Gok+hM0A37/3bgvLaCIdXgbJAb0Qb6hRsiZRSmC1XZC7APCYlmj/7k3JikNbbLtbjlLbxyq9nMNVj",
	"QoOh21+yZDwVqmDJpCwPXaynx/iCqNGMKZS1gX5O5Q78Gw0/qCubR5b04IcfFhJmjD/D0zLl8mH24eVP",
	"hJMTsMwJ258AU5OlwUhX9ehxZTDiy6RPZOQTwc5z1xo6l4U5glB9XZNLfjx773svtIUnTw7oFPnkSQzM",
	"Q33/tFK8Ku0hC0yGuZ+fPLkhdtXB8dnZEZxhcpynh1LnHLbOjg+34WPOpOgXMxHoG5bitTYj7x/vh8LO",
	"yuZWu7nTbG/T0ZvBNZMj0pQdkZ20gkSPkQKl8Jw3YowKCZIpDmRz4b9RUpzZr2gJXM0MC4en56+8X+Y9",
	"ix9zAmkFdwvXQkpgnHt4FMMxS9FmLMEY/qbNiBBuDCeax56j74V01YJ2nHATGAnFCU9lGUWQ8uNZhKCb",
	"hBmnB4ZlQ0IjEzTWK+FHn12hr6XU1zDL71tX62ZJV9uF3fM0ZWaycP5oJKicEUmw4LKVYNVIc4PMsg0B",
	"hIG2YYmDk6Oo0paIvJF8tc9QsUxEnWjPP/IHkaHPPq2hb4P8Rp8H6FH+zGWPeNSJfkL3c0GyNNLdbbdv",
	"mKjdbZJWNGNqBmlnaMYiQe9qUoyxuZBHo87FZVW7M1/z3kVqYgNLOTpsM7qkl1v+lFnd8iLLv6IRfcpQ",
	"XF8r6wwyKt0ZQWOV0PMtzhzrMYvbHhUYZMmwrLIr2jsNzP7Tygsna6dD8xacYf2+SPwR72l77zFHoxWh",
	"lHZBsJuterqYNNaZdbzTKic1a92ZjrKHJVG8cI9nDfack7TCzZVpvJGwuHtDEPXBrF6dX9Voed0EaxpH",
	"+0GKusVn0rYqFzb8KzubX1mYtfuX9ja/NL/hsOQBi8jowjfeosvpUrjbWbfJVtxi9uhyGkeZtjWOEJpi",
	"5UQuADq07qXmk/s2UdF/my7iRmdynK74x859M6+9jFJ03YomJKWtITJexM0bHfjVjDZOj0pkpfBaTsoF",
	"qlea6q4I1WLo6R/YE+mN55vfmF0k2uC6HhAv++7pvAGXzLywxoGXMlvrs+DTYBpCxauO/co/rzr2goPt",
	"rx/thRV581HVvL/5jdl1og1qLjSypOegj01ajtein7WabD9mqM5aB/+ltqnL3j+h22yWu1Xo+U1cYuVb",
	"QTU3TSt9IospU04ktlP2eXTZ9jE69amup/nE47xq46dm9lg7D1h0p9DvumvRSefyfvtFjlW02W5VgB7F",
	"q4NAfGHQ8EeuBfcYCLW1IOhjqVNJpfZ2tcHPXm6EvMee4sHx7mbKulvUDwqTZ/OrjRi5mGB9fQBZFcYv",
	"HSh83wSN/SzuYXBxZSj9yKA4DBhXPcFPPe4NDpOCvyosfKf898jgWQU/XXbuamq8JWaeefwmwOy95StH",
	"y2vUuh4n12uv/Tih+/XC47V2uFspL/446KFR8frR6hfg5DtVoC8HyZVB9CMj5HUuXcLjUEf+j43XYeN1",
	"qf9GLmF5f4M5RM6i7qncS+A4Rqkzfw07jnIjixFdp9WSRDDU1nW+b3/f9hFVCLCy1E2DL9jKvfKR4oys",
	"7e9RFH98V7S1CU+vvb1WHgPW3v5b/otCe/N64c8Vt661GaGBFpCHGy0bmWQKIWXJkMTf9gMqoaq3xGaM",
	"ggGml9N/BwAA//8pD5mRLzsAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
