apiVersion: v1
kind: Service
metadata:
  name: argosd
  namespace: argos-system
  labels:
    app.kubernetes.io/name: argos
    app.kubernetes.io/component: daemon
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: argos
    app.kubernetes.io/component: daemon
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
