{{- if .Values.cnpg.enabled }}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ include "argos.fullname" . }}-pg
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "argos.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  instances: {{ .Values.cnpg.instances }}
  imageName: {{ .Values.cnpg.imageName }}

  bootstrap:
    initdb:
      database: {{ .Values.cnpg.database }}
      owner: {{ .Values.cnpg.owner }}

  storage:
    size: {{ .Values.cnpg.storageSize }}
    {{- if .Values.cnpg.storageClass }}
    storageClass: {{ .Values.cnpg.storageClass }}
    {{- end }}
{{- end }}
